flag_value {
  package: "android.content.res"
  name: "default_locale"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: resource_manager
  # bug: 117306409
  # description: Feature flag for default locale in LocaleConfig
  # trace: frameworks/base/core/java/android/content/res/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.content.res/default_locale_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.content.res/default_locale_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.content.res/default_locale_flag_values.textproto : ENABLED
}
