flag_value {
  package: "android.content.res"
  name: "use_new_aconfig_storage"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: resource_manager
  # purpose: PURPOSE_BUGFIX
  # bug: 352348353
  # description: Retrieve flag values from new Aconfig flag storage in AconfigFlags.java
  # trace: frameworks/base/core/java/android/content/res/flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/android.content.res/use_new_aconfig_storage_flag_values.textproto : ENABLED
}
