flag_value {
  package: "com.android.org.conscrypt.flags"
  name: "certificate_transparency_platform"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.conscrypt
  # namespace: core_libraries
  # bug: 319829948
  # description: This flag controls whether conscrypt will interpret the NetworkSecurityConfig for Certificate Transparency
  # trace: external/conscrypt/conscrypt.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.org.conscrypt.flags/certificate_transparency_platform_flag_values.textproto : ENABLED
}
