flag_value {
  package: "android.app.supervision.flags"
  name: "supervision_api_on_wear"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/android.app.supervision.flags/supervision_api_on_wear_flag_values.textproto : ENABLED
}
