flag_value {
  package: "com.android.graphics.surfaceflinger.flags"
  name: "reject_dupe_layerstacks"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.graphics.surfaceflinger.flags/reject_dupe_layerstacks_flag_values.textproto : ENABLED
}
