flag_value {
  package: "com.android.input.flags"
  name: "device_associations"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: input
  # bug: 324075859
  # description: Binds InputDevice name and InputDevice description against display unique id.
  # trace: frameworks/native/libs/input/input_flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap4a/com.android.input.flags/device_associations_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.input.flags/device_associations_flag_values.textproto : ENABLED
}
