# build/release/aconfig/bp2a/com.android.internal.telephony.flags/add_rat_related_suggested_action_to_ims_registration_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.internal.telephony.flags"
  name: "add_rat_related_suggested_action_to_ims_registration"
  state: ENABLED
  permission: READ_ONLY
}
