# build/release/aconfig/bp2a/com.android.internal.telephony.flags/carrier_id_from_carrier_identifier_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.internal.telephony.flags"
  name: "carrier_id_from_carrier_identifier"
  state: ENABLED
  permission: READ_ONLY
}
