# build/release/aconfig/bp2a/com.android.internal.telephony.flags/force_imsi_certificate_delete_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.internal.telephony.flags"
  name: "force_imsi_certificate_delete"
  state: ENABLED
  permission: READ_ONLY
}
