flag_value {
  package: "com.android.internal.telephony.flags"
  name: "incall_handover_policy"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.internal.telephony.flags/incall_handover_policy_flag_values.textproto : ENABLED
}
