# build/release/aconfig/bp2a/com.android.internal.telephony.flags/skip_mmi_code_check_for_emergency_call_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.internal.telephony.flags"
  name: "skip_mmi_code_check_for_emergency_call"
  state: ENABLED
  permission: READ_ONLY
}
