# build/release/aconfig/bp2a/com.android.internal.telephony.flags/starlink_data_bugfix_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.internal.telephony.flags"
  name: "starlink_data_bugfix"
  state: ENABLED
  permission: READ_ONLY
}
