# build/release/aconfig/bp2a/com.android.internal.telephony.flags/temporary_failures_in_carrier_messaging_service_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.internal.telephony.flags"
  name: "temporary_failures_in_carrier_messaging_service"
  state: ENABLED
  permission: READ_ONLY
}
