# build/release/aconfig/bp2a/com.android.media.aaudio/offload_support_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.media.aaudio"
  name: "offload_support"
  state: ENABLED
  permission: READ_ONLY
}
