flag_value {
  package: "com.android.server.flags"
  name: "disable_system_compaction"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: system_performance
  # bug: 314328789
  # description: This flag controls if all processes compaction should happen during idle maintenance.
  # trace: frameworks/base/services/core/java/com/android/server/flags/compaction.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.server.flags/disable_system_compaction_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.server.flags/disable_system_compaction_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.server.flags/disable_system_compaction_flag_values.textproto : ENABLED
}
