flag_value {
  package: "android.nfc"
  name: "enable_nfc_set_discovery_tech"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: nfc
  # bug: 300351519
  # description: Flag for NFC set discovery tech API
  # trace: frameworks/base/nfc-non-updatable/flags/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.nfc/enable_nfc_set_discovery_tech_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.nfc/enable_nfc_set_discovery_tech_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.nfc/enable_nfc_set_discovery_tech_flag_values.textproto : ENABLED
}
