flag_value {
  package: "android.nfc"
  name: "nfc_read_polling_loop_st_shim"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: nfc
  # bug: 294217286
  # description: Enable NFC Polling Loop Notifications ST shim
  # trace: frameworks/base/nfc-non-updatable/flags/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.nfc/nfc_read_polling_loop_st_shim_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.nfc/nfc_read_polling_loop_st_shim_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.nfc/nfc_read_polling_loop_st_shim_flag_values.textproto : ENABLED
}
