flag_value {
  package: "android.nfc"
  name: "nfc_check_tag_intent_preference"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: nfc
  # bug: 335916336
  # description: App can check its tag intent preference status
  # trace: frameworks/base/nfc-non-updatable/flags/flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/android.nfc/nfc_check_tag_intent_preference_flag_values.textproto : ENABLED
}
