flag_value {
  package: "android.nfc"
  name: "nfc_persist_log"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: nfc
  # bug: 321310044
  # description: Enable NFC persistent log support
  # trace: frameworks/base/nfc-non-updatable/flags/flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/android.nfc/nfc_persist_log_flag_values.textproto : ENABLED
}
