flag_value {
  package: "android.nfc"
  name: "nfc_state_change_security_log_event_enabled"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: nfc
  # bug: 319934052
  # description: Enabling security log for nfc state change
  # trace: frameworks/base/nfc-non-updatable/flags/flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/android.nfc/nfc_state_change_security_log_event_enabled_flag_values.textproto : ENABLED
}
