# build/release/aconfig/bp2a/android.view.contentcapture.flags/flush_after_each_frame_flag_values.textproto : ENABLED
flag_value {
  package: "android.view.contentcapture.flags"
  name: "flush_after_each_frame"
  state: ENABLED
  permission: READ_ONLY
}
