flag_value {
  package: "com.android.nfc.flags"
  name: "send_view_intent_for_url_tag_dispatch"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: nfc
  # bug: 345570691
  # description: Send VIEW intent instead of NFC_TAG_DISCOVERED for URL tag dispatch
  # trace: packages/modules/Nfc/NfcNci/flags/nfc_flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.nfc.flags/send_view_intent_for_url_tag_dispatch_flag_values.textproto : ENABLED
}
