flag_value {
  package: "com.android.nfc.flags"
  name: "statsd_ce_events_flag"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: nfc
  # bug: 308094195
  # description: Additional Statsd CardEmulation Events flag for NFC
  # trace: packages/modules/Nfc/NfcNci/flags/nfc_flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.nfc.flags/statsd_ce_events_flag_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.nfc.flags/statsd_ce_events_flag_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.nfc.flags/statsd_ce_events_flag_flag_values.textproto : ENABLED
}
