flag_value {
  package: "com.google.android.pixelsystemservice.wirelesscharger.flags"
  name: "enable_system_flags_transmission"
  state: ENABLED
  permission: READ_ONLY
  # container: system_ext
  # namespace: pixel_energizer
  # purpose: PURPOSE_BUGFIX
  # bug: 374874807
  # description: Whether to enable the system flags transmission
  # trace: vendor/google/apps/PersistentBackgroundServices/wirelesscharger/aconfig/flags.aconfig : DISABLED
  # trace: vendor/google/release/aconfig/bp2a/com.google.android.pixelsystemservice.wirelesscharger.flags/enable_system_flags_transmission_flag_values.textproto : ENABLED
}
