flag_value {
  package: "com.android.internal.telephony.flags"
  name: "clear_cached_ims_phone_number_when_device_lost_ims_registration"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: telephony
  # bug: 288002989
  # description: This flag clears cached IMS phone number when device lost IMS registration
  # trace: frameworks/opt/telephony/flags/ims.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.internal.telephony.flags/clear_cached_ims_phone_number_when_device_lost_ims_registration_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.internal.telephony.flags/clear_cached_ims_phone_number_when_device_lost_ims_registration_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.internal.telephony.flags/clear_cached_ims_phone_number_when_device_lost_ims_registration_flag_values.textproto : ENABLED
}
