flag_value {
  package: "com.android.internal.telephony.flags"
  name: "emergency_callback_mode_notification"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: telephony
  # bug: 359064059
  # description: Used to notify the emergency callback mode for call/SMS to other applications.
  # trace: frameworks/opt/telephony/flags/calling.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.internal.telephony.flags/emergency_callback_mode_notification_flag_values.textproto : ENABLED
}
