flag_value {
  package: "com.android.internal.telephony.flags"
  name: "esim_available_memory"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: telephony
  # bug: 318348580
  # description: This flag controls eSIM available memory feature.
  # trace: frameworks/opt/telephony/flags/uicc.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.internal.telephony.flags/esim_available_memory_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.internal.telephony.flags/esim_available_memory_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.internal.telephony.flags/esim_available_memory_flag_values.textproto : ENABLED
}
