flag_value {
  package: "com.android.internal.telephony.flags"
  name: "hide_prefer_3g_item"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: telephony
  # bug: 310639009
  # description: Used in the Preferred Network Types menu to determine if the 3G option is displayed.
  # trace: frameworks/opt/telephony/flags/network.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.internal.telephony.flags/hide_prefer_3g_item_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.internal.telephony.flags/hide_prefer_3g_item_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.internal.telephony.flags/hide_prefer_3g_item_flag_values.textproto : ENABLED
}
