flag_value {
  package: "com.android.internal.telephony.flags"
  name: "log_mms_sms_database_access_info"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: telephony
  # bug: 275225402
  # description: Whether to log MMS/SMS database access info and report anomaly when getting exception.
  # trace: frameworks/opt/telephony/flags/misc.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.internal.telephony.flags/log_mms_sms_database_access_info_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.internal.telephony.flags/log_mms_sms_database_access_info_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.internal.telephony.flags/log_mms_sms_database_access_info_flag_values.textproto : ENABLED
}
