flag_value {
  package: "com.android.internal.telephony.flags"
  name: "network_validation"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: telephony
  # bug: 286171724
  # description: Request network validation for data networks and response status.
  # trace: frameworks/opt/telephony/flags/data.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.internal.telephony.flags/network_validation_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.internal.telephony.flags/network_validation_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.internal.telephony.flags/network_validation_flag_values.textproto : ENABLED
}
