flag_value {
  package: "com.android.internal.telephony.flags"
  name: "oem_enabled_satellite_flag"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: telephony
  # bug: 291811962
  # description: This flag controls satellite communication supported by OEMs.
  # trace: frameworks/opt/telephony/flags/satellite.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.internal.telephony.flags/oem_enabled_satellite_flag_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.internal.telephony.flags/oem_enabled_satellite_flag_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.internal.telephony.flags/oem_enabled_satellite_flag_flag_values.textproto : ENABLED
}
