flag_value {
  package: "com.android.internal.telephony.flags"
  name: "phone_type_cleanup"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: telephony
  # purpose: PURPOSE_BUGFIX
  # bug: 379356026
  # description: As CDMA deprecated, there is no need to switch phone type between CDMA and GSM
  # trace: frameworks/opt/telephony/flags/misc.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.internal.telephony.flags/phone_type_cleanup_flag_values.textproto : ENABLED
}
