flag_value {
  package: "com.android.internal.telephony.flags"
  name: "remap_disconnect_cause_sip_request_cancelled"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: telephony
  # purpose: PURPOSE_BUGFIX
  # bug: 351258918
  # description: Fix dialer UI bug by remapping disconnect CODE_SIP_REQUEST_CANCELLED to DisconnectCause.NORMAL
  # trace: frameworks/opt/telephony/flags/calling.aconfig : DISABLED
  # trace: build/release/aconfig/ap4a/com.android.internal.telephony.flags/remap_disconnect_cause_sip_request_cancelled_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.internal.telephony.flags/remap_disconnect_cause_sip_request_cancelled_flag_values.textproto : ENABLED
}
