flag_value {
  package: "com.android.internal.telephony.flags"
  name: "reset_mobile_network_settings"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: telephony
  # bug: 271921464
  # description: Allows applications to launch Reset Mobile Network Settings page in Settings app.
  # trace: frameworks/opt/telephony/flags/misc.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.internal.telephony.flags/reset_mobile_network_settings_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.internal.telephony.flags/reset_mobile_network_settings_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.internal.telephony.flags/reset_mobile_network_settings_flag_values.textproto : ENABLED
}
