flag_value {
  package: "com.android.internal.telephony.flags"
  name: "satellite_data_metrics"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: telephony
  # purpose: PURPOSE_BUGFIX
  # bug: 405107194
  # description: Support Satellite Data metrics at satellite session
  # trace: frameworks/opt/telephony/flags/satellite.aconfig : DISABLED
  # trace: build/release/aconfig/bp3a/com.android.internal.telephony.flags/satellite_data_metrics_flag_values.textproto : ENABLED
}
