flag_value {
  package: "com.android.internal.telephony.flags"
  name: "security_algorithms_update_indications"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: telephony
  # bug: 355062720
  # description: guard system API onSecurityAlgorithmsChanged
  # trace: frameworks/opt/telephony/flags/network.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.internal.telephony.flags/security_algorithms_update_indications_flag_values.textproto : ENABLED
}
