flag_value {
  package: "com.android.internal.telephony.flags"
  name: "simultaneous_calling_indications"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: telephony
  # bug: 297446980
  # description: APIs that are used to notify simultaneous calling changes to other applications.
  # trace: frameworks/opt/telephony/flags/calling.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.internal.telephony.flags/simultaneous_calling_indications_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.internal.telephony.flags/simultaneous_calling_indications_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.internal.telephony.flags/simultaneous_calling_indications_flag_values.textproto : ENABLED
}
