flag_value {
  package: "com.android.internal.telephony.flags"
  name: "slicing_additional_error_codes"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: telephony
  # bug: 307378699
  # description: Support additional slicing error codes and functionality.
  # trace: frameworks/opt/telephony/flags/data.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.internal.telephony.flags/slicing_additional_error_codes_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.internal.telephony.flags/slicing_additional_error_codes_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.internal.telephony.flags/slicing_additional_error_codes_flag_values.textproto : ENABLED
}
