flag_value {
  package: "com.android.internal.telephony.flags"
  name: "terminate_active_video_call_when_accepting_second_video_call_as_audio_only"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: telephony
  # bug: 309548300
  # description: This flag terminates active video call instead holding when accepting 2nd incoming video call as audio only
  # trace: frameworks/opt/telephony/flags/ims.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.internal.telephony.flags/terminate_active_video_call_when_accepting_second_video_call_as_audio_only_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.internal.telephony.flags/terminate_active_video_call_when_accepting_second_video_call_as_audio_only_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.internal.telephony.flags/terminate_active_video_call_when_accepting_second_video_call_as_audio_only_flag_values.textproto : ENABLED
}
