flag_value {
  package: "com.android.permission.flags"
  name: "cross_user_role_enabled"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.permission.flags/cross_user_role_enabled_flag_values.textproto : ENABLED
}
