flag_value {
  package: "com.android.permission.flags"
  name: "odad_notifications_supported"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.permission.flags/odad_notifications_supported_flag_values.textproto : ENABLED
}
