flag_value {
  package: "com.android.server.telecom.flags"
  name: "add_call_uri_for_missed_calls"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: telecom
  # bug: 292597423
  # description: The key is used for dialer apps to mark missed calls as read when it gets the notification on reboot.
  # trace: packages/services/Telecomm/flags/telecom_api_flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.server.telecom.flags/add_call_uri_for_missed_calls_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.server.telecom.flags/add_call_uri_for_missed_calls_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.server.telecom.flags/add_call_uri_for_missed_calls_flag_values.textproto : ENABLED
}
