flag_value {
  package: "com.android.server.telecom.flags"
  name: "cache_call_events"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: telecom
  # purpose: PURPOSE_BUGFIX
  # bug: 364311190
  # description: Cache call events to wait for the ServiceWrapper to be set
  # trace: packages/services/Telecomm/flags/telecom_call_flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap4a/com.android.server.telecom.flags/cache_call_events_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.server.telecom.flags/cache_call_events_flag_values.textproto : ENABLED
}
