flag_value {
  package: "com.android.server.telecom.flags"
  name: "call_details_id_changes"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: telecom
  # bug: 301713560
  # description: When set, call details/extras id updates to Telecom APIs for Android V are active.
  # trace: packages/services/Telecomm/flags/telecom_api_flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.server.telecom.flags/call_details_id_changes_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.server.telecom.flags/call_details_id_changes_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.server.telecom.flags/call_details_id_changes_flag_values.textproto : ENABLED
}
