flag_value {
  package: "com.android.server.telecom.flags"
  name: "communication_device_protected_by_lock"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: telecom
  # bug: 303001133
  # description: Protect set/clear communication device operation with lock to avoid race condition.
  # trace: packages/services/Telecomm/flags/telecom_callaudioroutestatemachine_flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.server.telecom.flags/communication_device_protected_by_lock_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.server.telecom.flags/communication_device_protected_by_lock_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.server.telecom.flags/communication_device_protected_by_lock_flag_values.textproto : ENABLED
}
