flag_value {
  package: "com.android.server.telecom.flags"
  name: "ensure_audio_mode_updates_on_foreground_call_change"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: telecom
  # bug: 289861657
  # description: Ensure that the audio mode is updated anytime the foreground call changes.
  # trace: packages/services/Telecomm/flags/telecom_callaudioroutestatemachine_flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.server.telecom.flags/ensure_audio_mode_updates_on_foreground_call_change_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.server.telecom.flags/ensure_audio_mode_updates_on_foreground_call_change_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.server.telecom.flags/ensure_audio_mode_updates_on_foreground_call_change_flag_values.textproto : ENABLED
}
