flag_value {
  package: "com.android.server.telecom.flags"
  name: "set_mute_state"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: telecom
  # bug: 310669304
  # description: transactional calls need the ability to mute the call audio input
  # trace: packages/services/Telecomm/flags/telecom_api_flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.server.telecom.flags/set_mute_state_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.server.telecom.flags/set_mute_state_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.server.telecom.flags/set_mute_state_flag_values.textproto : ENABLED
}
