flag_value {
  package: "com.android.server.telecom.flags"
  name: "voip_app_actions_support"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: telecom
  # bug: 296934278
  # description: When set, Telecom support for additional VOIP application actions is active.
  # trace: packages/services/Telecomm/flags/telecom_api_flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.server.telecom.flags/voip_app_actions_support_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.server.telecom.flags/voip_app_actions_support_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.server.telecom.flags/voip_app_actions_support_flag_values.textproto : ENABLED
}
