flag_value {
  package: "android.hardware.biometrics"
  name: "identity_check_api"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/android.hardware.biometrics/identity_check_api_flag_values.textproto : ENABLED
}
