# build/release/aconfig/bp2a/android.hardware.biometrics/private_space_bp_flag_values.textproto : ENABLED
flag_value {
  package: "android.hardware.biometrics"
  name: "private_space_bp"
  state: ENABLED
  permission: READ_ONLY
}
