flag_value {
  package: "android.media.audio"
  name: "cache_get_stream_min_max_volume"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: media_audio
  # bug: 383667500
  # description: Cache getStream[Min|Max]Volume calls between AudioManager and AudioService
  # trace: frameworks/av/media/audio/aconfig/audio_framework.aconfig : DISABLED
  # trace: build/release/aconfig/bp3a/android.media.audio/cache_get_stream_min_max_volume_flag_values.textproto : ENABLED
}
