flag_value {
  package: "android.media.audio"
  name: "focus_exclusive_with_recording"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: media_audio
  # bug: 316414750
  # description: Audio focus GAIN_TRANSIENT_EXCLUSIVE only mutesnotifications when the focus owner is also recording
  # trace: frameworks/av/media/audio/aconfig/audio_framework.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.media.audio/focus_exclusive_with_recording_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.media.audio/focus_exclusive_with_recording_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.media.audio/focus_exclusive_with_recording_flag_values.textproto : ENABLED
}
