flag_value {
  package: "android.media.audio"
  name: "muted_by_port_volume_api"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: media_audio
  # bug: 319515324
  # description: Playback monitoring flag used when player muted by port volume
  # trace: frameworks/av/media/audio/aconfig/audio_framework.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/android.media.audio/muted_by_port_volume_api_flag_values.textproto : ENABLED
}
