flag_value {
  package: "android.media.audio"
  name: "routed_device_ids"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: media_audio
  # bug: 367816690
  # description: Enable Java and native functions to getmultiple routed device ids
  # trace: frameworks/av/media/audio/aconfig/audio_framework.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/android.media.audio/routed_device_ids_flag_values.textproto : ENABLED
}
