# build/release/aconfig/bp2a/android.crashrecovery.flags/enable_crashrecovery_flag_values.textproto : ENABLED
flag_value {
  package: "android.crashrecovery.flags"
  name: "enable_crashrecovery"
  state: ENABLED
  permission: READ_ONLY
}
