flag_value {
  package: "com.android.media.flags"
  name: "avoid_binder_calls_during_render"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: media_better_together
  # purpose: PURPOSE_BUGFIX
  # bug: 414668703
  # description: Reduces number of expensive binder calls during rendering.
  # trace: frameworks/base/media/java/android/media/flags/media_better_together.aconfig : DISABLED
  # trace: build/release/aconfig/bp3a/com.android.media.flags/avoid_binder_calls_during_render_flag_values.textproto : ENABLED
}
