flag_value {
  package: "com.android.media.flags"
  name: "enable_cross_user_routing_in_media_router2"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: media_solutions
  # bug: 288580225
  # description: Allows clients of privileged MediaRouter2 that hold INTERACT_ACROSS_USERS_FULL to control routing across users.
  # trace: frameworks/base/media/java/android/media/flags/media_better_together.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.media.flags/enable_cross_user_routing_in_media_router2_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.media.flags/enable_cross_user_routing_in_media_router2_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.media.flags/enable_cross_user_routing_in_media_router2_flag_values.textproto : ENABLED
}
