# build/release/aconfig/bp2a/android.appwidget.flags/remote_document_support_flag_values.textproto : ENABLED
flag_value {
  package: "android.appwidget.flags"
  name: "remote_document_support"
  state: ENABLED
  permission: READ_ONLY
}
