# build/release/aconfig/bp2a/android.appwidget.flags/remote_views_proto_flag_values.textproto : ENABLED
flag_value {
  package: "android.appwidget.flags"
  name: "remote_views_proto"
  state: ENABLED
  permission: READ_ONLY
}
