# build/release/aconfig/bp2a/android.appwidget.flags/remote_adapter_conversion_flag_values.textproto : ENABLED
flag_value {
  package: "android.appwidget.flags"
  name: "remote_adapter_conversion"
  state: ENABLED
  permission: READ_ONLY
}
