flag_value {
  package: "android.appwidget.flags"
  name: "use_smaller_app_widget_system_radius"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/android.appwidget.flags/use_smaller_app_widget_system_radius_flag_values.textproto : ENABLED
}
