flag_value {
  package: "android.chre.flags"
  name: "bug_fix_remove_exit_call_in_hal"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/android.chre.flags/bug_fix_remove_exit_call_in_hal_flag_values.textproto : ENABLED
}
