flag_value {
  package: "com.android.server.backup"
  name: "enable_metrics_settings_backup_agents"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: onboarding
  # bug: 379861078
  # description: Enable SettingsBackupAgent to collect B&R agent metrics.
  # trace: frameworks/base/services/backup/flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.server.backup/enable_metrics_settings_backup_agents_flag_values.textproto : ENABLED
}
