flag_value {
  package: "com.google.wear.services.infra.flags"
  name: "enable_cross_stack_n10n_debug_logging"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: wear_services
  # bug: 277762129
  # description: Enables cross stack debug logging for Wear Services.
  # trace: vendor/google_clockwork_partners/packages/WearServices/src/com/google/wear/services/infra/flags/wear_services_flags.aconfig : DISABLED
  # trace: vendor/google/release/aconfig/ap3a/com.google.wear.services.infra.flags/enable_cross_stack_n10n_debug_logging_flag_values.textproto : ENABLED
}
