flag_value {
  package: "com.google.wear.services.infra.flags"
  name: "restrict_complications_telemetry_flag"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: wear_services
  # bug: 292057151
  # description: Enables restricting non-DWF 3P watch faces feature telemetry
  # trace: vendor/google_clockwork_partners/packages/WearServices/src/com/google/wear/services/infra/flags/wear_services_flags.aconfig : DISABLED
  # trace: vendor/google/release/aconfig/ap3a/com.google.wear.services.infra.flags/restrict_complications_telemetry_flag_flag_values.textproto : ENABLED
}
