flag_value {
  package: "android.media.tv.flags"
  name: "media_quality_fw"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: media_tv
  # bug: 348412562
  # description: Media Quality V1.0 APIs for Android W
  # trace: frameworks/base/media/java/android/media/tv/flags/media_tv.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/android.media.tv.flags/media_quality_fw_flag_values.textproto : ENABLED
}
