# build/release/aconfig/bp2a/android.nfc/nfc_oem_extension_flag_values.textproto : ENABLED
flag_value {
  package: "android.nfc"
  name: "nfc_oem_extension"
  state: ENABLED
  permission: READ_ONLY
}
