# build/release/aconfig/bp2a/android.nfc/nfc_override_recover_routing_table_flag_values.textproto : ENABLED
flag_value {
  package: "android.nfc"
  name: "nfc_override_recover_routing_table"
  state: ENABLED
  permission: READ_ONLY
}
