# build/release/aconfig/bp2a/android.nfc/nfc_check_tag_intent_preference_flag_values.textproto : ENABLED
flag_value {
  package: "android.nfc"
  name: "nfc_check_tag_intent_preference"
  state: ENABLED
  permission: READ_ONLY
}
