flag_value {
  package: "android.nfc"
  name: "nfc_state_change"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/android.nfc/nfc_state_change_flag_values.textproto : ENABLED
}
