flag_value {
  package: "android.nfc"
  name: "nfc_associated_role_services"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/android.nfc/nfc_associated_role_services_flag_values.textproto : ENABLED
}
