# build/release/aconfig/bp2a/android.nfc/nfc_event_listener_flag_values.textproto : ENABLED
flag_value {
  package: "android.nfc"
  name: "nfc_event_listener"
  state: ENABLED
  permission: READ_ONLY
}
