flag_value {
  package: "com.android.server.display.feature.flags"
  name: "enable_pixel_anisotropy_correction"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: display_manager
  # bug: 317363416
  # description: Feature flag for enabling display anisotropy correction through LogicalDisplay upscaling
  # trace: frameworks/base/services/core/java/com/android/server/display/feature/display_flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.server.display.feature.flags/enable_pixel_anisotropy_correction_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.server.display.feature.flags/enable_pixel_anisotropy_correction_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.server.display.feature.flags/enable_pixel_anisotropy_correction_flag_values.textproto : ENABLED
}
