flag_value {
  package: "com.android.server.display.feature.flags"
  name: "framerate_override_triggers_rr_callbacks"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: display_manager
  # purpose: PURPOSE_BUGFIX
  # bug: 390113266
  # description: Feature flag to trigger the RR callbacks when framerate overridding happens.
  # trace: frameworks/base/services/core/java/com/android/server/display/feature/display_flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.server.display.feature.flags/framerate_override_triggers_rr_callbacks_flag_values.textproto : ENABLED
}
