flag_value {
  package: "com.android.server.display.feature.flags"
  name: "highest_hdr_sdr_ratio_api"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: display_manager
  # bug: 335181559
  # description: Feature flag for an API to get the highest defined HDR/SDR ratio for a display.
  # trace: frameworks/base/services/core/java/com/android/server/display/feature/display_flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.server.display.feature.flags/highest_hdr_sdr_ratio_api_flag_values.textproto : ENABLED
}
