flag_value {
  package: "com.android.server.display.feature.flags"
  name: "new_hdr_brightness_modifier"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: display_manager
  # bug: 331275392
  # description: Flag for new HDR brightness clamper.
  # trace: frameworks/base/services/core/java/com/android/server/display/feature/display_flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp1a/com.android.server.display.feature.flags/new_hdr_brightness_modifier_flag_values.textproto : ENABLED
}
