flag_value {
  package: "com.android.server.display.feature.flags"
  name: "normal_brightness_for_doze_parameter"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: wear_frameworks
  # bug: 343283838
  # description: Feature flag for the parameter specifying whether brightness should be adjusted while dozing.
  # trace: frameworks/base/services/core/java/com/android/server/display/feature/display_flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.server.display.feature.flags/normal_brightness_for_doze_parameter_flag_values.textproto : ENABLED
}
