flag_value {
  package: "com.android.server.display.feature.flags"
  name: "resolution_backup_restore"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: display_manager
  # bug: 321821289
  # description: Backup/Restore support for High Resolution setting
  # trace: frameworks/base/services/core/java/com/android/server/display/feature/display_flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.server.display.feature.flags/resolution_backup_restore_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.server.display.feature.flags/resolution_backup_restore_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.server.display.feature.flags/resolution_backup_restore_flag_values.textproto : ENABLED
}
