flag_value {
  package: "com.android.server.display.feature.flags"
  name: "sensor_based_brightness_throttling"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: display_manager
  # bug: 294900859
  # description: Feature flag for enabling brightness throttling using sensor from config.
  # trace: frameworks/base/services/core/java/com/android/server/display/feature/display_flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.server.display.feature.flags/sensor_based_brightness_throttling_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.server.display.feature.flags/sensor_based_brightness_throttling_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.server.display.feature.flags/sensor_based_brightness_throttling_flag_values.textproto : ENABLED
}
