flag_value {
  package: "com.android.server.display.feature.flags"
  name: "subscribe_granular_display_events"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: display_manager
  # purpose: PURPOSE_BUGFIX
  # bug: 379250634
  # description: Enable subscription to granular display change events.
  # trace: frameworks/base/services/core/java/com/android/server/display/feature/display_flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.server.display.feature.flags/subscribe_granular_display_events_flag_values.textproto : ENABLED
}
