# build/release/aconfig/bp2a/com.android.wm.shell/enable_task_view_controller_cleanup_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.wm.shell"
  name: "enable_task_view_controller_cleanup"
  state: ENABLED
  permission: READ_ONLY
}
