flag_value {
  package: "android.app.contextualsearch.flags"
  name: "contextual_search_prevent_self_capture"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: sysui_integrations
  # purpose: PURPOSE_BUGFIX
  # bug: 390176823
  # description: Identify live contextual search UI to exclude from contextual search screenshot.
  # trace: frameworks/base/core/java/android/app/contextualsearch/flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/android.app.contextualsearch.flags/contextual_search_prevent_self_capture_flag_values.textproto : ENABLED
}
