flag_value {
  package: "com.android.adservices.ondevicepersonalization.flags"
  name: "executorch_inference_api_enabled"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.ondevicepersonalization
  # namespace: ondevicepersonalization_aconfig
  # bug: 376942125
  # description: Enable executorch inference API.
  # trace: packages/modules/OnDevicePersonalization/flags/ondevicepersonalization_flags.aconfig : DISABLED
  # trace: vendor/google_shared/build/release/aconfig/mainline_2025_06/com.android.adservices.ondevicepersonalization.flags/executorch_inference_api_enabled_flag_values.textproto : ENABLED
}
