flag_value {
  package: "android.service.voice.flags"
  name: "allow_foreground_activities_in_on_show"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: machine_learning
  # bug: 319409708
  # description: This flag allows providing foreground app component along with onShow args.
  # trace: frameworks/base/core/java/android/service/voice/flags/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.service.voice.flags/allow_foreground_activities_in_on_show_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.service.voice.flags/allow_foreground_activities_in_on_show_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.service.voice.flags/allow_foreground_activities_in_on_show_flag_values.textproto : ENABLED
}
