flag_value {
  package: "com.android.server.telecom.flags"
  name: "csw_service_interface_is_null"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.server.telecom.flags/csw_service_interface_is_null_flag_values.textproto : ENABLED
}
