# build/release/aconfig/bp2a/com.android.server.telecom.flags/do_not_send_call_to_null_ics_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.server.telecom.flags"
  name: "do_not_send_call_to_null_ics"
  state: ENABLED
  permission: READ_ONLY
}
