# build/release/aconfig/bp2a/com.android.server.telecom.flags/enable_call_sequencing_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.server.telecom.flags"
  name: "enable_call_sequencing"
  state: ENABLED
  permission: READ_ONLY
}
