# build/release/aconfig/bp2a/com.android.server.telecom.flags/maybe_default_speaker_after_unhold_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.server.telecom.flags"
  name: "maybe_default_speaker_after_unhold"
  state: ENABLED
  permission: READ_ONLY
}
