# build/release/aconfig/bp2a/com.android.server.telecom.flags/unregister_unresolvable_accounts_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.server.telecom.flags"
  name: "unregister_unresolvable_accounts"
  state: ENABLED
  permission: READ_ONLY
}
