flag_value {
  package: "com.android.media.mediasession.flags"
  name: "remove_wiu_allowlisting_from_mediacontroller_sendcommand"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: media_solutions
  # bug: 339637822
  # description: Remove WIU allowlisting from MediaController.sendCommand
  # trace: frameworks/base/media/java/android/media/flags/mediasession.aconfig : DISABLED
  # trace: build/release/aconfig/bp3a/com.android.media.mediasession.flags/remove_wiu_allowlisting_from_mediacontroller_sendcommand_flag_values.textproto : ENABLED
}
