flag_value {
  package: "com.android.settings.media_drm"
  name: "force_l3_enabled"
  state: ENABLED
  permission: READ_ONLY
  # container: system_ext
  # namespace: media_drm
  # bug: 301669353
  # description: Feature flag of forcing L3
  # trace: packages/apps/Settings/aconfig/media_drm/settings_mediadrm_flag_declarations.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.settings.media_drm/force_l3_enabled_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.settings.media_drm/force_l3_enabled_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.settings.media_drm/force_l3_enabled_flag_values.textproto : ENABLED
}
