flag_value {
  package: "com.android.graphics.egl.flags"
  name: "multifile_blobcache_advanced_usage"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.graphics.egl.flags/multifile_blobcache_advanced_usage_flag_values.textproto : ENABLED
}
