flag_value {
  package: "android.multiuser"
  name: "cache_profile_parent_read_only"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/android.multiuser/cache_profile_parent_read_only_flag_values.textproto : ENABLED
}
