flag_value {
  package: "com.android.adservices.flags"
  name: "fledge_enable_report_event_for_component_seller"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.adservices
  # namespace: adservices_aconfig
  # bug: 377279411
  # description: Enables component seller as one of the destination for reporting event.
  # trace: packages/modules/AdServices/adservices/flags/adservices_flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.adservices.flags/fledge_enable_report_event_for_component_seller_flag_values.textproto : ENABLED
}
