flag_value {
  package: "com.android.shell.flags"
  name: "handle_bugreports_for_wear"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: wear_services
  # bug: 338029043
  # description: This flag enables Shell to propagate bugreport results to WearServices.
  # trace: frameworks/base/packages/Shell/aconfig/wear.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.shell.flags/handle_bugreports_for_wear_flag_values.textproto : ENABLED
}
