# build/release/aconfig/bp2a/com.android.server.accessibility/enable_magnification_keyboard_control_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.server.accessibility"
  name: "enable_magnification_keyboard_control"
  state: ENABLED
  permission: READ_ONLY
}
