flag_value {
  package: "com.google.android.settings.simplemode.flags"
  name: "matcha_enabled"
  state: ENABLED
  permission: READ_ONLY
  # container: system_ext
  # namespace: globalintl
  # bug: 341210043
  # description: This flag controls whether the simple mode v1.1 and v1.5 should be enabled
  # trace: vendor/unbundled_google/packages/SettingsGoogle/SimpleMode/aconfig/settings_pixel_globalintl_flag_declarations.aconfig : DISABLED
  # trace: vendor/google/release/aconfig/ap4a/com.google.android.settings.simplemode.flags/matcha_enabled_flag_values.textproto : ENABLED
  # trace: vendor/google/release/aconfig/bp1a/com.google.android.settings.simplemode.flags/matcha_enabled_flag_values.textproto : ENABLED
}
