flag_value {
  package: "com.android.sdksandbox.flags"
  name: "sandbox_client_importance_listener"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.sdksandbox.flags/sandbox_client_importance_listener_flag_values.textproto : ENABLED
}
