flag_value {
  package: "com.android.healthfitness.flags"
  name: "clear_caches_after_switching_user"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.healthfitness
  # namespace: health_fitness_aconfig
  # purpose: PURPOSE_BUGFIX
  # bug: 355426144
  # description: Enables clearing database caches after switching users.
  # trace: packages/modules/HealthFitness/flags/healthfitness-flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.healthfitness.flags/clear_caches_after_switching_user_flag_values.textproto : ENABLED
}
