flag_value {
  package: "com.android.healthfitness.flags"
  name: "ecosystem_metrics_db_changes"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.healthfitness
  # namespace: health_fitness_aconfig
  # bug: 369507783
  # description: Enables DB modification to allow collection of ecosystem metrics.
  # trace: packages/modules/HealthFitness/flags/healthfitness-flags.aconfig : DISABLED
  # trace: vendor/google_shared/build/release/aconfig/mainline_2025_06/com.android.healthfitness.flags/ecosystem_metrics_db_changes_flag_values.textproto : ENABLED
}
