flag_value {
  package: "com.android.healthfitness.flags"
  name: "mindfulness"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.healthfitness
  # namespace: health_fitness_aconfig
  # bug: 341704006
  # description: Enables mindfulness session data type.
  # trace: packages/modules/HealthFitness/flags/healthfitness-flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.healthfitness.flags/mindfulness_flag_values.textproto : ENABLED
}
