flag_value {
  package: "com.android.healthfitness.flags"
  name: "phr_fhir_validation_disallow_empty_objects_arrays"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.healthfitness
  # namespace: health_fitness_aconfig
  # bug: 382469576
  # description: Flag for disallowing empty objects and arrays.
  # trace: packages/modules/HealthFitness/flags/healthfitness-flags.aconfig : DISABLED
  # trace: vendor/google_shared/build/release/aconfig/mainline_2025_06/com.android.healthfitness.flags/phr_fhir_validation_disallow_empty_objects_arrays_flag_values.textproto : ENABLED
}
