flag_value {
  package: "com.android.server.stats"
  name: "add_mobile_bytes_transfer_by_proc_state_puller"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: statsd
  # bug: 309512867
  # description: Adds mobile_bytes_transfer_by_proc_state atom with system server side aggregation
  # trace: frameworks/base/services/core/java/com/android/server/stats/stats_flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.server.stats/add_mobile_bytes_transfer_by_proc_state_puller_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.server.stats/add_mobile_bytes_transfer_by_proc_state_puller_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.server.stats/add_mobile_bytes_transfer_by_proc_state_puller_flag_values.textproto : ENABLED
}
