flag_value {
  package: "android.os"
  name: "message_queue_testability"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: system_performance
  # bug: 379472827
  # description: Whether MessageQueue implements test APIs.
  # trace: frameworks/base/core/java/android/os/flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/android.os/message_queue_testability_flag_values.textproto : ENABLED
}
