# build/release/aconfig/bp2a/com.android.server.usb.flags/check_user_action_unlocked_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.server.usb.flags"
  name: "check_user_action_unlocked"
  state: ENABLED
  permission: READ_ONLY
}
