# build/release/aconfig/bp2a/com.android.server.usb.flags/maximize_usb_audio_volume_when_connecting_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.server.usb.flags"
  name: "maximize_usb_audio_volume_when_connecting"
  state: ENABLED
  permission: READ_ONLY
}
