# build/release/aconfig/bp2a/android.media.tv.flags/broadcast_visibility_types_flag_values.textproto : ENABLED
flag_value {
  package: "android.media.tv.flags"
  name: "broadcast_visibility_types"
  state: ENABLED
  permission: READ_ONLY
}
