# build/release/aconfig/bp2a/android.media.tv.flags/mediacas_update_client_profile_priority_flag_values.textproto : ENABLED
flag_value {
  package: "android.media.tv.flags"
  name: "mediacas_update_client_profile_priority"
  state: ENABLED
  permission: READ_ONLY
}
