# build/release/aconfig/bp2a/android.media.tv.flags/tiaf_v_apis_flag_values.textproto : ENABLED
flag_value {
  package: "android.media.tv.flags"
  name: "tiaf_v_apis"
  state: ENABLED
  permission: READ_ONLY
}
