# build/release/aconfig/bp2a/android.app.wearable/enable_concurrent_wearable_connections_flag_values.textproto : ENABLED
flag_value {
  package: "android.app.wearable"
  name: "enable_concurrent_wearable_connections"
  state: ENABLED
  permission: READ_ONLY
}
