# build/release/aconfig/bp2a/com.android.server.power.feature.flags/policy_reason_in_display_power_request_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.server.power.feature.flags"
  name: "policy_reason_in_display_power_request"
  state: ENABLED
  permission: READ_ONLY
}
