flag_value {
  package: "com.android.healthfitness.flags"
  name: "phr_upsert_fix_parcel_size_calculation"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.healthfitness.flags/phr_upsert_fix_parcel_size_calculation_flag_values.textproto : ENABLED
}
