flag_value {
  package: "android.companion.virtual.flags"
  name: "persistent_device_id_api"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: virtual_devices
  # bug: 295258915
  # description: Enable persistent device ID notification API
  # trace: frameworks/base/core/java/android/companion/virtual/flags/deprecated_flags_do_not_edit.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.companion.virtual.flags/persistent_device_id_api_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.companion.virtual.flags/persistent_device_id_api_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.companion.virtual.flags/persistent_device_id_api_flag_values.textproto : ENABLED
}
