flag_value {
  package: "android.companion.virtual.flags"
  name: "vdm_custom_home"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: virtual_devices
  # bug: 297168328
  # description: Enable custom home API
  # trace: frameworks/base/core/java/android/companion/virtual/flags/deprecated_flags_do_not_edit.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.companion.virtual.flags/vdm_custom_home_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.companion.virtual.flags/vdm_custom_home_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.companion.virtual.flags/vdm_custom_home_flag_values.textproto : ENABLED
}
