flag_value {
  package: "android.app.usage"
  name: "get_app_bytes_by_data_type_api"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: system_performance
  # bug: 294088945
  # description: Feature flag for collecting app data size by file type API
  # trace: frameworks/base/core/java/android/app/usage/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.app.usage/get_app_bytes_by_data_type_api_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.app.usage/get_app_bytes_by_data_type_api_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.app.usage/get_app_bytes_by_data_type_api_flag_values.textproto : ENABLED
}
