# build/release/aconfig/bp2a/android.widget.flags/enable_fading_view_group_flag_values.textproto : ENABLED
flag_value {
  package: "android.widget.flags"
  name: "enable_fading_view_group"
  state: ENABLED
  permission: READ_ONLY
}
