# build/release/aconfig/bp2a/android.widget.flags/use_wear_material3_ui_flag_values.textproto : ENABLED
flag_value {
  package: "android.widget.flags"
  name: "use_wear_material3_ui"
  state: ENABLED
  permission: READ_ONLY
}
