flag_value {
  package: "com.android.uwb.flags"
  name: "hybrid_session_support"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.uwb
  # namespace: uwb
  # bug: 293919345
  # description: This flag controls hybrid session configuration support
  # trace: packages/modules/Uwb/flags/uwb_flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.uwb.flags/hybrid_session_support_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.uwb.flags/hybrid_session_support_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.uwb.flags/hybrid_session_support_flag_values.textproto : ENABLED
}
