flag_value {
  package: "com.android.bluetooth.flags"
  name: "avdt_handle_suspend_cfm_bad_state"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.bt
  # namespace: bluetooth
  # purpose: PURPOSE_BUGFIX
  # bug: 377830155
  # description: Close connection on AVDTP Suspend Confirmation with BAD STATE error
  # trace: packages/modules/Bluetooth/flags/a2dp.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.bluetooth.flags/avdt_handle_suspend_cfm_bad_state_flag_values.textproto : ENABLED
}
