flag_value {
  package: "com.android.bluetooth.flags"
  name: "bonded_device_smp_failure_handling"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.bt
  # namespace: bluetooth
  # purpose: PURPOSE_BUGFIX
  # bug: 385181815
  # description: Don't remove bond on SMP failure for bonded devices in peripheral role
  # trace: packages/modules/Bluetooth/flags/pairing.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.bluetooth.flags/bonded_device_smp_failure_handling_flag_values.textproto : ENABLED
}
