flag_value {
  package: "com.android.bluetooth.flags"
  name: "channel_sounding"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.bt
  # namespace: bluetooth
  # bug: 317683528
  # description: Enable Channel Sounding
  # trace: packages/modules/Bluetooth/flags/ranging.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.bluetooth.flags/channel_sounding_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.bluetooth.flags/channel_sounding_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.bluetooth.flags/channel_sounding_flag_values.textproto : ENABLED
}
