flag_value {
  package: "com.android.bluetooth.flags"
  name: "configure_scan_on_resume"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.bt
  # namespace: bluetooth
  # purpose: PURPOSE_BUGFIX
  # bug: 383436218
  # description: Configure scan paramters when start scanning from onResume
  # trace: packages/modules/Bluetooth/flags/gap.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.bluetooth.flags/configure_scan_on_resume_flag_values.textproto : ENABLED
}
