flag_value {
  package: "com.android.bluetooth.flags"
  name: "dsa_hw_transparent_codec"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.bt
  # namespace: bluetooth
  # purpose: PURPOSE_BUGFIX
  # bug: 382263607
  # description: Use trasparent codec for DSA hardware path
  # trace: packages/modules/Bluetooth/flags/leaudio.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.bluetooth.flags/dsa_hw_transparent_codec_flag_values.textproto : ENABLED
}
