flag_value {
  package: "com.android.bluetooth.flags"
  name: "fix_execute_write_no_pending"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.bt
  # namespace: bluetooth
  # purpose: PURPOSE_BUGFIX
  # bug: 385118069
  # description: Send ATT_EXECUTE_WRITE_RSP when no pending write requests
  # trace: packages/modules/Bluetooth/flags/gap.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.bluetooth.flags/fix_execute_write_no_pending_flag_values.textproto : ENABLED
}
