flag_value {
  package: "com.android.bluetooth.flags"
  name: "gatt_queue_cleanup_connected"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.bt
  # namespace: bluetooth
  # purpose: PURPOSE_BUGFIX
  # bug: 379007400
  # description: Cleans up BtaGattQueue when connected
  # trace: packages/modules/Bluetooth/flags/gap.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.bluetooth.flags/gatt_queue_cleanup_connected_flag_values.textproto : ENABLED
}
