flag_value {
  package: "com.android.bluetooth.flags"
  name: "le_ase_read_multiple_variable"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.bt
  # namespace: bluetooth
  # purpose: PURPOSE_BUGFIX
  # bug: 352085435
  # description: Use GATT read multiple variable length characteristic values
  # trace: packages/modules/Bluetooth/flags/leaudio.aconfig : DISABLED
  # trace: build/release/aconfig/ap4a/com.android.bluetooth.flags/le_ase_read_multiple_variable_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.bluetooth.flags/le_ase_read_multiple_variable_flag_values.textproto : ENABLED
}
