flag_value {
  package: "com.android.bluetooth.flags"
  name: "le_enc_on_reconnect"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.bt
  # namespace: bluetooth
  # purpose: PURPOSE_BUGFIX
  # bug: 388864535
  # description: Encrypt LE link on reconnection with bonded devices
  # trace: packages/modules/Bluetooth/flags/security.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.bluetooth.flags/le_enc_on_reconnect_flag_values.textproto : ENABLED
}
