flag_value {
  package: "com.android.bluetooth.flags"
  name: "leaudio_broadcast_receive_state_processing_refactor"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.bt
  # namespace: bluetooth
  # purpose: PURPOSE_BUGFIX
  # bug: 380231464
  # description: Fix parsing empty receive states and refactor its processing
  # trace: packages/modules/Bluetooth/flags/leaudio.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.bluetooth.flags/leaudio_broadcast_receive_state_processing_refactor_flag_values.textproto : ENABLED
}
