flag_value {
  package: "com.android.bluetooth.flags"
  name: "leaudio_multiple_vocs_instances_api"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.bt
  # namespace: bluetooth
  # bug: 323156655
  # description: Support multiple audio outputs for volume offset
  # trace: packages/modules/Bluetooth/flags/leaudio.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.bluetooth.flags/leaudio_multiple_vocs_instances_api_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.bluetooth.flags/leaudio_multiple_vocs_instances_api_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.bluetooth.flags/leaudio_multiple_vocs_instances_api_flag_values.textproto : ENABLED
}
