flag_value {
  package: "com.android.bluetooth.flags"
  name: "leaudio_use_audio_recording_listener"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.bt
  # namespace: bluetooth
  # purpose: PURPOSE_BUGFIX
  # bug: 381054654
  # description: Use Audio Recording listener instead of monitoring sink session
  # trace: packages/modules/Bluetooth/flags/leaudio.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.bluetooth.flags/leaudio_use_audio_recording_listener_flag_values.textproto : ENABLED
}
