flag_value {
  package: "com.android.bluetooth.flags"
  name: "metadata_api_microphone_for_call_enabled"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.bt
  # namespace: bluetooth
  # bug: 372395197
  # description: API to get and set microphone for call enable status
  # trace: packages/modules/Bluetooth/flags/leaudio.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.bluetooth.flags/metadata_api_microphone_for_call_enabled_flag_values.textproto : ENABLED
}
