flag_value {
  package: "com.android.bluetooth.flags"
  name: "rfcomm_always_disc_initiator_in_disc_wait_ua"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.bt
  # namespace: bluetooth
  # purpose: PURPOSE_BUGFIX
  # bug: 350839022
  # description: Always be the DISC initiator in the DISC_WAIT_UA state to avoid unnecessary hang
  # trace: packages/modules/Bluetooth/flags/rfcomm.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.bluetooth.flags/rfcomm_always_disc_initiator_in_disc_wait_ua_flag_values.textproto : ENABLED
}
