flag_value {
  package: "com.android.bluetooth.flags"
  name: "vup_for_pending_connection"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.bt
  # namespace: bluetooth
  # purpose: PURPOSE_BUGFIX
  # bug: 396747085
  # description: Generate HID VUP for pending connections as well
  # trace: packages/modules/Bluetooth/flags/hid.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.bluetooth.flags/vup_for_pending_connection_flag_values.textproto : ENABLED
}
