flag_value {
  package: "android.location.flags"
  name: "gnss_api_measurement_request_work_source"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: location
  # bug: 295235160
  # description: Flag for GnssMeasurementRequest WorkSource API
  # trace: frameworks/base/location/java/android/location/flags/location.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.location.flags/gnss_api_measurement_request_work_source_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.location.flags/gnss_api_measurement_request_work_source_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.location.flags/gnss_api_measurement_request_work_source_flag_values.textproto : ENABLED
}
