flag_value {
  package: "android.location.flags"
  name: "population_density_provider"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: location
  # bug: 376198890
  # description: Flag for enabling the population density provider
  # trace: frameworks/base/location/java/android/location/flags/location.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/android.location.flags/population_density_provider_flag_values.textproto : ENABLED
}
