flag_value {
  package: "com.android.appsearch.flags"
  name: "enable_set_publicly_visible_schema"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.appsearch
  # namespace: appsearch
  # bug: 325262525
  # description: Enable setPubliclyVisibleSchema API in SetSchemaRequest.
  # trace: packages/modules/AppSearch/flags/appsearch.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.appsearch.flags/enable_set_publicly_visible_schema_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.appsearch.flags/enable_set_publicly_visible_schema_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.appsearch.flags/enable_set_publicly_visible_schema_flag_values.textproto : ENABLED
}
