flag_value {
  package: "com.android.appsearch.flags"
  name: "enable_batch_put"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.appsearch
  # namespace: appsearch
  # purpose: PURPOSE_BUGFIX
  # bug: 394875109
  # description: Uses the new batch put API from Icing.
  # trace: packages/modules/AppSearch/flags/appsearch.aconfig : DISABLED
  # trace: vendor/google_shared/build/release/aconfig/mainline_2025_06/com.android.appsearch.flags/enable_batch_put_flag_values.textproto : ENABLED
}
