flag_value {
  package: "com.android.appsearch.flags"
  name: "enable_embedding_match_info"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.appsearch
  # namespace: appsearch
  # bug: 395128139
  # description: Enables the option to retrieve embedding match info during snippetting.
  # trace: packages/modules/AppSearch/flags/appsearch.aconfig : DISABLED
  # trace: vendor/google_shared/build/release/aconfig/mainline_2025_06/com.android.appsearch.flags/enable_embedding_match_info_flag_values.textproto : ENABLED
}
