flag_value {
  package: "com.android.appsearch.flags"
  name: "enable_additional_builder_copy_constructors"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.appsearch
  # namespace: appsearch
  # bug: 369563892
  # description: Enables additional builder copy constructors for AppSearchSchema, SetSchemaRequest, SearchSpec, JoinSpec, AppSearchBatchResult, and GetSchemaResponse.
  # trace: packages/modules/AppSearch/flags/appsearch.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.appsearch.flags/enable_additional_builder_copy_constructors_flag_values.textproto : ENABLED
}
