flag_value {
  package: "com.android.appsearch.flags"
  name: "enable_document_limiter_replace_tracking"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.appsearch
  # namespace: appsearch
  # bug: 363301147
  # description: Enables the replacement of the calculation of doc limits.
  # trace: packages/modules/AppSearch/flags/appsearch.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.appsearch.flags/enable_document_limiter_replace_tracking_flag_values.textproto : ENABLED
}
