flag_value {
  package: "com.android.appsearch.flags"
  name: "enable_release_backup_schema_file_if_overlay_present"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.appsearch
  # namespace: appsearch
  # purpose: PURPOSE_BUGFIX
  # bug: 396436137
  # description: Enable releasing the backup schema file instance in the schema store if the overlay schema instance exists.
  # trace: packages/modules/AppSearch/flags/appsearch.aconfig : DISABLED
  # trace: vendor/google_shared/build/release/aconfig/mainline_2025_06/com.android.appsearch.flags/enable_release_backup_schema_file_if_overlay_present_flag_values.textproto : ENABLED
}
