flag_value {
  package: "com.android.appsearch.flags"
  name: "enable_marker_file_for_optimize"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.appsearch
  # namespace: appsearch
  # purpose: PURPOSE_BUGFIX
  # bug: 385021899
  # description: Enable marker file creation for Optimize API.
  # trace: packages/modules/AppSearch/flags/appsearch.aconfig : DISABLED
  # trace: vendor/google_shared/build/release/aconfig/mainline_2025_06/com.android.appsearch.flags/enable_marker_file_for_optimize_flag_values.textproto : ENABLED
}
