flag_value {
  package: "com.android.appsearch.flags"
  name: "enable_soft_index_restoration"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.appsearch
  # namespace: appsearch
  # bug: 384947619
  # description: Enable soft index restoration.
  # trace: packages/modules/AppSearch/flags/appsearch.aconfig : DISABLED
  # trace: vendor/google_shared/build/release/aconfig/mainline_2025_06/com.android.appsearch.flags/enable_soft_index_restoration_flag_values.textproto : ENABLED
}
