flag_value {
  package: "com.android.appsearch.flags"
  name: "enable_generic_document_copy_constructor"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.appsearch
  # namespace: appsearch
  # bug: 171882200
  # description: Enable GenericDocument to take another GenericDocument to copy construct.
  # trace: packages/modules/AppSearch/flags/appsearch.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.appsearch.flags/enable_generic_document_copy_constructor_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.appsearch.flags/enable_generic_document_copy_constructor_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.appsearch.flags/enable_generic_document_copy_constructor_flag_values.textproto : ENABLED
}
