flag_value {
  package: "com.android.appsearch.flags"
  name: "enable_app_search_manage_blob_files"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.appsearch
  # namespace: appsearch
  # purpose: PURPOSE_BUGFIX
  # bug: 392140774
  # description: Enable AppSearch to manage blob files.
  # trace: packages/modules/AppSearch/flags/appsearch.aconfig : DISABLED
  # trace: vendor/google_shared/build/release/aconfig/mainline_2025_06/com.android.appsearch.flags/enable_app_search_manage_blob_files_flag_values.textproto : ENABLED
}
