# build/release/aconfig/bp2a/com.android.graphics.flags/ok_lab_colorspace_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.graphics.flags"
  name: "ok_lab_colorspace"
  state: ENABLED
  permission: READ_ONLY
}
