flag_value {
  package: "android.graphics.pdf.flags.readonly"
  name: "enable_edit_pdf_stamp_annotations"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.mediaprovider
  # namespace: pdf_viewer
  # bug: 379008090
  # description: This flag controls whether to enable stamp annotations editing support.
  # trace: packages/providers/MediaProvider/pdf/framework/pdf_viewer_flags_readonly.aconfig : DISABLED
  # trace: vendor/google_shared/build/release/aconfig/mainline_2025_06/android.graphics.pdf.flags.readonly/enable_edit_pdf_stamp_annotations_flag_values.textproto : ENABLED
}
