# build/release/aconfig/bp2a/com.android.server.flags/rate_limit_battery_changed_broadcast_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.server.flags"
  name: "rate_limit_battery_changed_broadcast"
  state: ENABLED
  permission: READ_ONLY
}
