flag_value {
  package: "android.media.audiopolicy"
  name: "audio_mix_test_api"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: media_audio
  # bug: 309080867
  # description: Enable new Test APIs that provide access to registered AudioMixes on system server and native side.
  # trace: frameworks/av/media/audio/aconfig/audiopolicy_framework.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.media.audiopolicy/audio_mix_test_api_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.media.audiopolicy/audio_mix_test_api_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.media.audiopolicy/audio_mix_test_api_flag_values.textproto : ENABLED
}
