flag_value {
  package: "com.android.graphics.libgui.flags"
  name: "apply_picture_profiles"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.graphics.libgui.flags/apply_picture_profiles_flag_values.textproto : ENABLED
}
