flag_value {
  package: "com.android.ranging.flags"
  name: "ranging_cs_enabled"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.ranging.flags/ranging_cs_enabled_flag_values.textproto : ENABLED
}
