# build/release/aconfig/bp2a/android.net.platform.flags/deprecate_network_policy_callback_flag_values.textproto : ENABLED
flag_value {
  package: "android.net.platform.flags"
  name: "deprecate_network_policy_callback"
  state: ENABLED
  permission: READ_ONLY
}
