# build/release/aconfig/bp2a/android.server/remove_game_manager_service_from_wear_flag_values.textproto : ENABLED
flag_value {
  package: "android.server"
  name: "remove_game_manager_service_from_wear"
  state: ENABLED
  permission: READ_ONLY
}
