flag_value {
  package: "com.android.appsearch.flags"
  name: "app_open_event_indexer_enabled"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.appsearch.flags/app_open_event_indexer_enabled_flag_values.textproto : ENABLED
}
