flag_value {
  package: "com.android.appsearch.flags"
  name: "enable_scorable_property"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.appsearch.flags/enable_scorable_property_flag_values.textproto : ENABLED
}
