flag_value {
  package: "com.android.appsearch.flags"
  name: "enable_schema_embedding_quantization"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.appsearch.flags/enable_schema_embedding_quantization_flag_values.textproto : ENABLED
}
