# build/release/aconfig/bp2a/com.android.graphics.hwui.flags/iso_gainmap_apis_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.graphics.hwui.flags"
  name: "iso_gainmap_apis"
  state: ENABLED
  permission: READ_ONLY
}
