flag_value {
  package: "com.android.graphics.hwui.flags"
  name: "runtime_color_filters_blenders"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.graphics.hwui.flags/runtime_color_filters_blenders_flag_values.textproto : ENABLED
}
