flag_value {
  package: "android.service.chooser"
  name: "chooser_album_text"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: intentresolver
  # bug: 323380224
  # description: Flag controlling the album text subtype hint for sharesheet
  # trace: frameworks/base/core/java/android/service/chooser/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.service.chooser/chooser_album_text_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.service.chooser/chooser_album_text_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.service.chooser/chooser_album_text_flag_values.textproto : ENABLED
}
