flag_value {
  package: "android.service.chooser"
  name: "chooser_payload_toggling"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: intentresolver
  # bug: 302691505
  # description: This flag controls content toggling in Chooser
  # trace: frameworks/base/core/java/android/service/chooser/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.service.chooser/chooser_payload_toggling_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.service.chooser/chooser_payload_toggling_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.service.chooser/chooser_payload_toggling_flag_values.textproto : ENABLED
}
