# build/release/aconfig/bp2a/android.sdk/major_minor_versioning_scheme_flag_values.textproto : ENABLED
flag_value {
  package: "android.sdk"
  name: "major_minor_versioning_scheme"
  state: ENABLED
  permission: READ_ONLY
}
