flag_value {
  package: "com.android.systemui"
  name: "face_scanning_animation_npe_fix"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.systemui/face_scanning_animation_npe_fix_flag_values.textproto : ENABLED
}
