# build/release/aconfig/bp2a/com.android.systemui/floating_menu_display_cutout_support_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.systemui"
  name: "floating_menu_display_cutout_support"
  state: ENABLED
  permission: READ_ONLY
}
