# build/release/aconfig/bp2a/com.android.systemui/media_controls_a11y_colors_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.systemui"
  name: "media_controls_a11y_colors"
  state: ENABLED
  permission: READ_ONLY
}
