# build/release/aconfig/bp2a/com.android.systemui/notification_appear_nonlinear_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.systemui"
  name: "notification_appear_nonlinear"
  state: ENABLED
  permission: READ_ONLY
}
