flag_value {
  package: "com.android.systemui"
  name: "only_show_media_stream_slider_in_single_volume_mode"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.systemui/only_show_media_stream_slider_in_single_volume_mode_flag_values.textproto : ENABLED
}
