# build/release/aconfig/bp2a/com.android.systemui/screenshot_policy_split_and_desktop_mode_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.systemui"
  name: "screenshot_policy_split_and_desktop_mode"
  state: ENABLED
  permission: READ_ONLY
}
