# build/release/aconfig/bp2a/com.android.systemui/shade_launch_accessibility_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.systemui"
  name: "shade_launch_accessibility"
  state: ENABLED
  permission: READ_ONLY
}
