# build/release/aconfig/bp2a/com.android.systemui/shade_expands_on_status_bar_long_press_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.systemui"
  name: "shade_expands_on_status_bar_long_press"
  state: ENABLED
  permission: READ_ONLY
}
