# build/release/aconfig/bp2a/com.android.systemui/status_bar_signal_policy_refactor_ethernet_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.systemui"
  name: "status_bar_signal_policy_refactor_ethernet"
  state: ENABLED
  permission: READ_ONLY
}
