# build/release/aconfig/bp2a/com.android.systemui/use_notif_inflation_thread_for_row_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.systemui"
  name: "use_notif_inflation_thread_for_row"
  state: ENABLED
  permission: READ_ONLY
}
