# build/release/aconfig/bp2a/com.android.systemui/user_aware_settings_repositories_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.systemui"
  name: "user_aware_settings_repositories"
  state: ENABLED
  permission: READ_ONLY
}
