flag_value {
  package: "com.android.media.audioserver"
  name: "enable_gmap_mode"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: media_audio
  # bug: 366456949
  # description: enable track metadata tag generation for GMAP.
  # trace: frameworks/av/media/audio/aconfig/audioserver.aconfig : DISABLED
  # trace: build/release/aconfig/bp3a/com.android.media.audioserver/enable_gmap_mode_flag_values.textproto : ENABLED
}
