# build/release/aconfig/bp2a/com.android.server.job/additional_quota_for_system_installer_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.server.job"
  name: "additional_quota_for_system_installer"
  state: ENABLED
  permission: READ_ONLY
}
