# build/release/aconfig/bp2a/com.android.server.job/adjust_quota_default_constants_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.server.job"
  name: "adjust_quota_default_constants"
  state: ENABLED
  permission: READ_ONLY
}
