# build/release/aconfig/bp2a/com.android.server.display.feature.flags/enable_battery_stats_for_all_displays_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.server.display.feature.flags"
  name: "enable_battery_stats_for_all_displays"
  state: ENABLED
  permission: READ_ONLY
}
