# build/release/aconfig/bp2a/com.android.server.display.feature.flags/highest_hdr_sdr_ratio_api_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.server.display.feature.flags"
  name: "highest_hdr_sdr_ratio_api"
  state: ENABLED
  permission: READ_ONLY
}
