flag_value {
  package: "android.media.codec"
  name: "p210_format_support"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/android.media.codec/p210_format_support_flag_values.textproto : ENABLED
}
