# build/release/aconfig/bp2a/android.media.codec/thumbnail_block_model_flag_values.textproto : ENABLED
flag_value {
  package: "android.media.codec"
  name: "thumbnail_block_model"
  state: ENABLED
  permission: READ_ONLY
}
