# build/release/aconfig/bp2a/com.android.input.flags/allow_transfer_of_entire_gesture_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.input.flags"
  name: "allow_transfer_of_entire_gesture"
  state: ENABLED
  permission: READ_ONLY
}
