# build/release/aconfig/bp2a/com.android.input.flags/enable_input_policy_profile_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.input.flags"
  name: "enable_input_policy_profile"
  state: ENABLED
  permission: READ_ONLY
}
