# build/release/aconfig/bp2a/android.os.vibrator/haptic_feedback_input_source_customization_enabled_flag_values.textproto : ENABLED
flag_value {
  package: "android.os.vibrator"
  name: "haptic_feedback_input_source_customization_enabled"
  state: ENABLED
  permission: READ_ONLY
}
