flag_value {
  package: "android.multiuser"
  name: "block_private_space_creation"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: profile_experiences
  # bug: 290333800
  # description: Allow blocking private space creation based on specific conditions
  # trace: frameworks/base/core/java/android/content/pm/multiuser.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.multiuser/block_private_space_creation_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.multiuser/block_private_space_creation_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.multiuser/block_private_space_creation_flag_values.textproto : ENABLED
}
