flag_value {
  package: "android.multiuser"
  name: "cache_user_info_read_only"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: multiuser
  # purpose: PURPOSE_BUGFIX
  # bug: 161915546
  # description: Cache UserInfo to avoid unnecessary binder calls
  # trace: frameworks/base/core/java/android/content/pm/multiuser.aconfig : DISABLED
  # trace: build/release/aconfig/bp3a/android.multiuser/cache_user_info_read_only_flag_values.textproto : ENABLED
}
