flag_value {
  package: "android.multiuser"
  name: "enable_private_space_intent_redirection"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: profile_experiences
  # bug: 325576602
  # description: Enable Private Space telephony and SMS intent redirection to the main user
  # trace: frameworks/base/core/java/android/content/pm/multiuser.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.multiuser/enable_private_space_intent_redirection_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.multiuser/enable_private_space_intent_redirection_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.multiuser/enable_private_space_intent_redirection_flag_values.textproto : ENABLED
}
