flag_value {
  package: "android.multiuser"
  name: "restrict_quiet_mode_credential_bug_fix_to_managed_profiles"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: profile_experiences
  # purpose: PURPOSE_BUGFIX
  # bug: 332812630
  # description: Use user states to check the state of quiet mode for managed profiles only
  # trace: frameworks/base/core/java/android/content/pm/multiuser.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.multiuser/restrict_quiet_mode_credential_bug_fix_to_managed_profiles_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.multiuser/restrict_quiet_mode_credential_bug_fix_to_managed_profiles_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.multiuser/restrict_quiet_mode_credential_bug_fix_to_managed_profiles_flag_values.textproto : ENABLED
}
