flag_value {
  package: "android.multiuser"
  name: "stop_previous_user_apps"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: multiuser
  # bug: 323200731
  # description: Stop the previous user apps early in a user switch
  # trace: frameworks/base/core/java/android/content/pm/multiuser.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/android.multiuser/stop_previous_user_apps_flag_values.textproto : ENABLED
}
