flag_value {
  package: "android.multiuser"
  name: "unicorn_mode_refactoring_for_hsum_read_only"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: multiuser
  # purpose: PURPOSE_BUGFIX
  # bug: 339201286
  # description: Refactorings related to unicorn mode to work on HSUM mode (Read only flag)
  # trace: frameworks/base/core/java/android/content/pm/multiuser.aconfig : DISABLED
  # trace: build/release/aconfig/ap4a/android.multiuser/unicorn_mode_refactoring_for_hsum_read_only_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.multiuser/unicorn_mode_refactoring_for_hsum_read_only_flag_values.textproto : ENABLED
}
