# build/release/aconfig/bp2a/com.android.tradeinmode.flags/enable_trade_in_mode_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.tradeinmode.flags"
  name: "enable_trade_in_mode"
  state: ENABLED
  permission: READ_ONLY
}
