flag_value {
  package: "com.android.window.flags"
  name: "app_compat_properties_api"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: large_screen_experiences_app_compat
  # bug: 316139088
  # description: Whether app compat property APIs are public. Which includes: /nWindowManager.PROPERTY_COMPAT_ALLOW_MIN_ASPECT_RATIO_OVERRIDE,/nWindowManager.PROPERTY_COMPAT_ALLOW_IGNORING_ORIENTATION_REQUEST_WHEN_LOOP_DETECTED,/nWindowManager.PROPERTY_COMPAT_ALLOW_RESIZEABLE_ACTIVITY_OVERRIDES,/nWindowManager.PROPERTY_COMPAT_ALLOW_USER_ASPECT_RATIO_OVERRIDE,/nWindowManager.PROPERTY_COMPAT_ALLOW_USER_ASPECT_RATIO_FULLSCREEN_OVERRIDE
  # trace: frameworks/base/core/java/android/window/flags/large_screen_experiences_app_compat.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.window.flags/app_compat_properties_api_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.window.flags/app_compat_properties_api_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.window.flags/app_compat_properties_api_flag_values.textproto : ENABLED
}
