flag_value {
  package: "com.android.window.flags"
  name: "bal_additional_start_modes"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: responsible_apis
  # bug: 352182359
  # description: Introduce additional start modes.
  # trace: frameworks/base/core/java/android/window/flags/responsible_apis.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.window.flags/bal_additional_start_modes_flag_values.textproto : ENABLED
}
