flag_value {
  package: "com.android.window.flags"
  name: "enable_desktop_windowing_scvh_cache_bug_fix"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: lse_desktop_experience
  # purpose: PURPOSE_BUGFIX
  # bug: 360452034
  # description: Enables a SurfaceControlViewHost cache for window decorations
  # trace: frameworks/base/core/java/android/window/flags/lse_desktop_experience.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.window.flags/enable_desktop_windowing_scvh_cache_bug_fix_flag_values.textproto : ENABLED
}
