flag_value {
  package: "com.android.window.flags"
  name: "enable_visual_indicator_in_transition_bugfix"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: lse_desktop_experience
  # purpose: PURPOSE_BUGFIX
  # bug: 392826275
  # description: Enables bugfix to move visual drop-zone indicator to transition root, so it can't be shown after the transition.
  # trace: frameworks/base/core/java/android/window/flags/lse_desktop_experience.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.window.flags/enable_visual_indicator_in_transition_bugfix_flag_values.textproto : ENABLED
}
