flag_value {
  package: "com.android.window.flags"
  name: "enable_task_stack_observer_in_shell"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: lse_desktop_experience
  # bug: 341932484
  # description: Introduces a new observer in shell to track the task stack.
  # trace: frameworks/base/core/java/android/window/flags/lse_desktop_experience.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.window.flags/enable_task_stack_observer_in_shell_flag_values.textproto : ENABLED
}
