flag_value {
  package: "com.android.window.flags"
  name: "enable_desktop_windowing_hsum"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: lse_desktop_experience
  # bug: 366397912
  # description: Enables HSUM on desktop mode.
  # trace: frameworks/base/core/java/android/window/flags/lse_desktop_experience.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.window.flags/enable_desktop_windowing_hsum_flag_values.textproto : ENABLED
}
