flag_value {
  package: "com.android.window.flags"
  name: "enable_app_header_with_task_density"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: lse_desktop_experience
  # bug: 332414819
  # description: Matches the App Header density to that of the app window, instead of SysUI's
  # trace: frameworks/base/core/java/android/window/flags/lse_desktop_experience.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.window.flags/enable_app_header_with_task_density_flag_values.textproto : ENABLED
}
