flag_value {
  package: "com.android.window.flags"
  name: "enable_window_context_resources_update_on_config_change"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: lse_desktop_experience
  # purpose: PURPOSE_BUGFIX
  # bug: 394527409
  # description: Updates window context resources before the view receives the config change callback.
  # trace: frameworks/base/core/java/android/window/flags/lse_desktop_experience.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.window.flags/enable_window_context_resources_update_on_config_change_flag_values.textproto : ENABLED
}
