flag_value {
  package: "com.android.window.flags"
  name: "enable_desktop_windowing_immersive_handle_hiding"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: lse_desktop_experience
  # bug: 336368019
  # description: Hides the App Handle when in fullscreen immersive mode
  # trace: frameworks/base/core/java/android/window/flags/lse_desktop_experience.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.window.flags/enable_desktop_windowing_immersive_handle_hiding_flag_values.textproto : ENABLED
}
