flag_value {
  package: "com.android.window.flags"
  name: "enable_accessible_custom_headers"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: lse_desktop_experience
  # purpose: PURPOSE_BUGFIX
  # bug: 339302584
  # description: Enables a11y-friendly custom header input handling
  # trace: frameworks/base/core/java/android/window/flags/lse_desktop_experience.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.window.flags/enable_accessible_custom_headers_flag_values.textproto : ENABLED
}
