flag_value {
  package: "com.android.window.flags"
  name: "enable_windowing_scaled_resizing"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: lse_desktop_experience
  # bug: 319844447
  # description: Enables the resizing of non-resizable apps through scaling their bounds up/down
  # trace: frameworks/base/core/java/android/window/flags/lse_desktop_experience.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.window.flags/enable_windowing_scaled_resizing_flag_values.textproto : ENABLED
}
