flag_value {
  package: "com.android.window.flags"
  name: "enable_desktop_windowing_persistence"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: lse_desktop_experience
  # bug: 350456942
  # description: Persists the desktop windowing session across reboots.
  # trace: frameworks/base/core/java/android/window/flags/lse_desktop_experience.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.window.flags/enable_desktop_windowing_persistence_flag_values.textproto : ENABLED
}
