flag_value {
  package: "com.android.window.flags"
  name: "enforce_edge_to_edge"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: windowing_frontend
  # bug: 309578419
  # description: Make app go edge-to-edge when targeting SDK level 35 or greater
  # trace: frameworks/base/core/java/android/window/flags/windowing_frontend.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.window.flags/enforce_edge_to_edge_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.window.flags/enforce_edge_to_edge_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.window.flags/enforce_edge_to_edge_flag_values.textproto : ENABLED
}
