flag_value {
  package: "com.android.window.flags"
  name: "jank_api"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: window_surfaces
  # bug: 293949943
  # description: Adds the jank data listener to AttachedSurfaceControl
  # trace: frameworks/base/core/java/android/window/flags/window_surfaces.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.window.flags/jank_api_flag_values.textproto : ENABLED
}
