flag_value {
  package: "com.android.window.flags"
  name: "movable_cutout_configuration"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: large_screen_experiences_app_compat
  # bug: 302387383
  # description: Make it possible to move cutout across edges through device config
  # trace: frameworks/base/core/java/android/window/flags/large_screen_experiences_app_compat.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.window.flags/movable_cutout_configuration_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.window.flags/movable_cutout_configuration_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.window.flags/movable_cutout_configuration_flag_values.textproto : ENABLED
}
