flag_value {
  package: "com.android.window.flags"
  name: "touch_pass_through_opt_in"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: windowing_sdk
  # bug: 358129114
  # description: Requires apps to opt-in to overlay pass through touches and provide APIs to opt-in
  # trace: frameworks/base/core/java/android/window/flags/windowing_sdk.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.window.flags/touch_pass_through_opt_in_flag_values.textproto : ENABLED
}
