flag_value {
  package: "android.hardware.flags"
  name: "overlayproperties_class_api"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: core_graphics
  # bug: 267234573
  # description: public OverlayProperties class, OverlayProperties#supportMixedColorSpaces and Display#getOverlaySupport API
  # trace: frameworks/base/core/java/android/hardware/flags/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.hardware.flags/overlayproperties_class_api_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.hardware.flags/overlayproperties_class_api_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.hardware.flags/overlayproperties_class_api_flag_values.textproto : ENABLED
}
