flag_value {
  package: "com.android.bluetooth.flags"
  name: "aics_api"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.bluetooth.flags/aics_api_flag_values.textproto : ENABLED
}
