flag_value {
  package: "com.android.bluetooth.flags"
  name: "directed_advertising_api"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.bluetooth.flags/directed_advertising_api_flag_values.textproto : ENABLED
}
