flag_value {
  package: "com.android.bluetooth.flags"
  name: "fix_execute_write_no_pending"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.bluetooth.flags/fix_execute_write_no_pending_flag_values.textproto : ENABLED
}
