flag_value {
  package: "com.android.bluetooth.flags"
  name: "ignore_notify_when_already_connected"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.bluetooth.flags/ignore_notify_when_already_connected_flag_values.textproto : ENABLED
}
