flag_value {
  package: "com.android.bluetooth.flags"
  name: "key_missing_as_ordered_broadcast"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.bluetooth.flags/key_missing_as_ordered_broadcast_flag_values.textproto : ENABLED
}
