flag_value {
  package: "com.android.bluetooth.flags"
  name: "leaudio_use_audio_recording_listener"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.bluetooth.flags/leaudio_use_audio_recording_listener_flag_values.textproto : ENABLED
}
