flag_value {
  package: "com.android.bluetooth.flags"
  name: "leaudio_gmap_client"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.bluetooth.flags/leaudio_gmap_client_flag_values.textproto : ENABLED
}
