flag_value {
  package: "com.android.bluetooth.flags"
  name: "leaudio_broadcast_primary_group_selection"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.bluetooth.flags/leaudio_broadcast_primary_group_selection_flag_values.textproto : ENABLED
}
