flag_value {
  package: "com.android.bluetooth.flags"
  name: "opp_check_content_uri_permissions"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.bluetooth.flags/opp_check_content_uri_permissions_flag_values.textproto : ENABLED
}
