flag_value {
  package: "com.android.bluetooth.flags"
  name: "support_metadata_device_types_apis"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.bluetooth.flags/support_metadata_device_types_apis_flag_values.textproto : ENABLED
}
