flag_value {
  package: "com.android.launcher3"
  name: "enable_grid_only_overview"
  state: ENABLED
  permission: READ_ONLY
  # container: system_ext
  # namespace: launcher_overview
  # bug: 360204325
  # description: Enable a grid-only overview without a focused task.
  # trace: packages/apps/Launcher3/aconfig/launcher_overview.aconfig : DISABLED
  # trace: build/release/aconfig/bp3a/com.android.launcher3/enable_grid_only_overview_flag_values.textproto : ENABLED
}
