flag_value {
  package: "com.android.launcher3"
  name: "enable_home_transition_listener"
  state: ENABLED
  permission: READ_ONLY
  # container: system_ext
  # namespace: launcher
  # bug: 306053414
  # description: Enables launcher to listen to all transitions that include home activity
  # trace: packages/apps/Launcher3/aconfig/launcher.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.launcher3/enable_home_transition_listener_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.launcher3/enable_home_transition_listener_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.launcher3/enable_home_transition_listener_flag_values.textproto : ENABLED
}
