flag_value {
  package: "com.android.launcher3"
  name: "enable_private_space_install_shortcut"
  state: ENABLED
  permission: READ_ONLY
  # container: system_ext
  # namespace: launcher
  # bug: 316118005
  # description: Enables long-press shortcut to install a copy of an app to Private space
  # trace: packages/apps/Launcher3/aconfig/launcher.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.launcher3/enable_private_space_install_shortcut_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.launcher3/enable_private_space_install_shortcut_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.launcher3/enable_private_space_install_shortcut_flag_values.textproto : ENABLED
}
