flag_value {
  package: "com.android.launcher3"
  name: "enable_focus_outline"
  state: ENABLED
  permission: READ_ONLY
  # container: system_ext
  # namespace: launcher
  # bug: 310953377
  # description: Enables focus states outline for launcher.
  # trace: packages/apps/Launcher3/aconfig/launcher.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.launcher3/enable_focus_outline_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.launcher3/enable_focus_outline_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.launcher3/enable_focus_outline_flag_values.textproto : ENABLED
}
