flag_value {
  package: "com.android.launcher3"
  name: "enable_add_app_widget_via_config_activity_v2"
  state: ENABLED
  permission: READ_ONLY
  # container: system_ext
  # namespace: launcher
  # purpose: PURPOSE_BUGFIX
  # bug: 284236964
  # description: When adding app widget through config activity, directly add it to workspace to reduce flicker
  # trace: packages/apps/Launcher3/aconfig/launcher.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.launcher3/enable_add_app_widget_via_config_activity_v2_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.launcher3/enable_add_app_widget_via_config_activity_v2_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.launcher3/enable_add_app_widget_via_config_activity_v2_flag_values.textproto : ENABLED
}
