flag_value {
  package: "com.android.launcher3"
  name: "enable_cursor_hover_states"
  state: ENABLED
  permission: READ_ONLY
  # container: system_ext
  # namespace: launcher
  # bug: 243191650
  # description: Enables cursor hover states for certain elements.
  # trace: packages/apps/Launcher3/aconfig/launcher.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.launcher3/enable_cursor_hover_states_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.launcher3/enable_cursor_hover_states_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.launcher3/enable_cursor_hover_states_flag_values.textproto : ENABLED
}
