flag_value {
  package: "com.android.launcher3"
  name: "enable_categorized_widget_suggestions"
  state: ENABLED
  permission: READ_ONLY
  # container: system_ext
  # namespace: launcher
  # bug: 318410881
  # description: Enables widget suggestions in widget picker to be displayed in categories
  # trace: packages/apps/Launcher3/aconfig/launcher.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.launcher3/enable_categorized_widget_suggestions_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.launcher3/enable_categorized_widget_suggestions_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.launcher3/enable_categorized_widget_suggestions_flag_values.textproto : ENABLED
}
