flag_value {
  package: "com.android.launcher3"
  name: "private_space_sys_apps_separation"
  state: ENABLED
  permission: READ_ONLY
  # container: system_ext
  # namespace: launcher_search
  # bug: 308054233
  # description: This flag enables showing system apps separate in Private Space container.
  # trace: packages/apps/Launcher3/aconfig/launcher_search.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.launcher3/private_space_sys_apps_separation_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.launcher3/private_space_sys_apps_separation_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.launcher3/private_space_sys_apps_separation_flag_values.textproto : ENABLED
}
