flag_value {
  package: "com.android.launcher3"
  name: "private_space_animation"
  state: ENABLED
  permission: READ_ONLY
  # container: system_ext
  # namespace: launcher_search
  # bug: 299294792
  # description: This flag enables the animation of the Private Space container
  # trace: packages/apps/Launcher3/aconfig/launcher_search.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.launcher3/private_space_animation_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.launcher3/private_space_animation_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.launcher3/private_space_animation_flag_values.textproto : ENABLED
}
