flag_value {
  package: "com.android.launcher3"
  name: "restore_archived_shortcuts"
  state: ENABLED
  permission: READ_ONLY
  # container: system_ext
  # namespace: launcher
  # purpose: PURPOSE_BUGFIX
  # bug: 375414891
  # description: Makes sure pre-archived pinned shortcuts also get restored
  # trace: packages/apps/Launcher3/aconfig/launcher.aconfig : DISABLED
  # trace: build/release/aconfig/bp3a/com.android.launcher3/restore_archived_shortcuts_flag_values.textproto : ENABLED
}
