flag_value {
  package: "com.android.launcher3"
  name: "work_scheduler_in_work_profile"
  state: ENABLED
  permission: READ_ONLY
  # container: system_ext
  # namespace: launcher
  # bug: 361589193
  # description: Enables work scheduler view above the work pause button in work profile.
  # trace: packages/apps/Launcher3/aconfig/launcher.aconfig : DISABLED
  # trace: build/release/aconfig/bp3a/com.android.launcher3/work_scheduler_in_work_profile_flag_values.textproto : ENABLED
}
