flag_value {
  package: "com.android.providers.media.flags"
  name: "motion_photo_intent"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.providers.media.flags/motion_photo_intent_flag_values.textproto : ENABLED
}
