flag_value {
  package: "android.view.inputmethod"
  name: "connectionless_handwriting"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: input_method
  # bug: 300979854
  # description: Feature flag for connectionless stylus handwriting APIs
  # trace: frameworks/base/core/java/android/view/inputmethod/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.view.inputmethod/connectionless_handwriting_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.view.inputmethod/connectionless_handwriting_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.view.inputmethod/connectionless_handwriting_flag_values.textproto : ENABLED
}
