flag_value {
  package: "android.view.inputmethod"
  name: "home_screen_handwriting_delegator"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: input_method
  # bug: 279959705
  # description: Feature flag for supporting stylus handwriting delegation from RemoteViews on the home screen
  # trace: frameworks/base/core/java/android/view/inputmethod/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.view.inputmethod/home_screen_handwriting_delegator_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.view.inputmethod/home_screen_handwriting_delegator_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.view.inputmethod/home_screen_handwriting_delegator_flag_values.textproto : ENABLED
}
