flag_value {
  package: "android.view.inputmethod"
  name: "use_zero_jank_proxy"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: input_method
  # bug: 293640003
  # description: Feature flag for using a proxy that uses async calls to achieve zero jank for IMMS calls.
  # trace: frameworks/base/core/java/android/view/inputmethod/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.view.inputmethod/use_zero_jank_proxy_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.view.inputmethod/use_zero_jank_proxy_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.view.inputmethod/use_zero_jank_proxy_flag_values.textproto : ENABLED
}
