flag_value {
  package: "com.android.net.flags"
  name: "ipsec_transform_state"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.tethering
  # namespace: android_core_networking_ipsec
  # bug: 308011229
  # description: The flag controls the access for getIpSecTransformState and IpSecTransformState
  # trace: packages/modules/Connectivity/common/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.net.flags/ipsec_transform_state_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.net.flags/ipsec_transform_state_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.net.flags/ipsec_transform_state_flag_values.textproto : ENABLED
}
