flag_value {
  package: "com.android.net.flags"
  name: "register_nsd_offload_engine_api"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.tethering
  # namespace: android_core_networking
  # bug: 301713539
  # description: Flag for API to register nsd offload engine
  # trace: packages/modules/Connectivity/common/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.net.flags/register_nsd_offload_engine_api_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.net.flags/register_nsd_offload_engine_api_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.net.flags/register_nsd_offload_engine_api_flag_values.textproto : ENABLED
}
