flag_value {
  package: "com.android.net.flags"
  name: "support_is_uid_networking_blocked"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.tethering
  # namespace: android_core_networking
  # bug: 297836825
  # description: This flag controls whether isUidNetworkingBlocked is supported
  # trace: packages/modules/Connectivity/common/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.net.flags/support_is_uid_networking_blocked_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.net.flags/support_is_uid_networking_blocked_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.net.flags/support_is_uid_networking_blocked_flag_values.textproto : ENABLED
}
