# build/release/aconfig/bp2a/android.companion.virtualdevice.flags/default_device_camera_access_policy_flag_values.textproto : ENABLED
flag_value {
  package: "android.companion.virtualdevice.flags"
  name: "default_device_camera_access_policy"
  state: ENABLED
  permission: READ_ONLY
}
