# build/release/aconfig/bp2a/android.companion.virtualdevice.flags/device_aware_display_power_flag_values.textproto : ENABLED
flag_value {
  package: "android.companion.virtualdevice.flags"
  name: "device_aware_display_power"
  state: ENABLED
  permission: READ_ONLY
}
