# build/release/aconfig/bp2a/android.companion.virtualdevice.flags/vdm_settings_flag_values.textproto : ENABLED
flag_value {
  package: "android.companion.virtualdevice.flags"
  name: "vdm_settings"
  state: ENABLED
  permission: READ_ONLY
}
