# build/release/aconfig/bp2a/android.companion.virtualdevice.flags/virtual_rotary_flag_values.textproto : ENABLED
flag_value {
  package: "android.companion.virtualdevice.flags"
  name: "virtual_rotary"
  state: ENABLED
  permission: READ_ONLY
}
