flag_value {
  package: "com.android.settingslib.flags"
  name: "audio_stream_play_pause_by_modify_source"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: cross_device_experiences
  # purpose: PURPOSE_BUGFIX
  # bug: 384976631
  # description: Play pause the audio stream by modify source
  # trace: frameworks/base/packages/SettingsLib/aconfig/settingslib.aconfig : DISABLED
  # trace: build/release/aconfig/bp3a/com.android.settingslib.flags/audio_stream_play_pause_by_modify_source_flag_values.textproto : ENABLED
}
