flag_value {
  package: "com.android.permission.flags"
  name: "private_profile_supported"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.permission
  # namespace: permissions
  # bug: 286539356
  # description: This flag is used to support private profile in safety center
  # trace: packages/modules/Permission/flags/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.permission.flags/private_profile_supported_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.permission.flags/private_profile_supported_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.permission.flags/private_profile_supported_flag_values.textproto : ENABLED
}
