# build/release/aconfig/bp2a/com.android.calllogbackup/call_log_restore_deduplication_enabled_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.calllogbackup"
  name: "call_log_restore_deduplication_enabled"
  state: ENABLED
  permission: READ_ONLY
}
