flag_value {
  package: "com.android.settingslib.flags"
  name: "hearing_device_set_connection_status_report"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.settingslib.flags/hearing_device_set_connection_status_report_flag_values.textproto : ENABLED
}
