# build/release/aconfig/bp2a/com.android.settingslib.flags/hearing_devices_ambient_volume_control_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.settingslib.flags"
  name: "hearing_devices_ambient_volume_control"
  state: ENABLED
  permission: READ_ONLY
}
