# build/release/aconfig/bp2a/android.adpf/adpf_viewrootimpl_action_down_boost_flag_values.textproto : ENABLED
flag_value {
  package: "android.adpf"
  name: "adpf_viewrootimpl_action_down_boost"
  state: ENABLED
  permission: READ_ONLY
}
