flag_value {
  package: "android.service.autofill"
  name: "autofill_credman_integration"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: autofill
  # bug: 296907283
  # description: Guards Autofill Framework against Autofill-Credman integration
  # trace: frameworks/base/services/autofill/features.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.service.autofill/autofill_credman_integration_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.service.autofill/autofill_credman_integration_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.service.autofill/autofill_credman_integration_flag_values.textproto : ENABLED
}
