flag_value {
  package: "com.android.icu"
  name: "icu_25q2_api"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.icu/icu_25q2_api_flag_values.textproto : ENABLED
}
