flag_value {
  package: "com.android.providers.settings"
  name: "support_local_overrides_sysprops"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.providers.settings/support_local_overrides_sysprops_flag_values.textproto : ENABLED
}
