# build/release/aconfig/bp2a/android.app.contextualsearch.flags/report_secure_surfaces_in_assist_structure_flag_values.textproto : ENABLED
flag_value {
  package: "android.app.contextualsearch.flags"
  name: "report_secure_surfaces_in_assist_structure"
  state: ENABLED
  permission: READ_ONLY
}
