# build/release/aconfig/bp2a/com.android.internal.camera.flags/ae_priority_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.internal.camera.flags"
  name: "ae_priority"
  state: ENABLED
  permission: READ_ONLY
}
