# build/release/aconfig/bp2a/com.android.internal.camera.flags/dumpsys_request_stream_ids_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.internal.camera.flags"
  name: "dumpsys_request_stream_ids"
  state: ENABLED
  permission: READ_ONLY
}
