# build/release/aconfig/bp2a/com.android.internal.camera.flags/feature_combination_baklava_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.internal.camera.flags"
  name: "feature_combination_baklava"
  state: ENABLED
  permission: READ_ONLY
}
