# build/release/aconfig/bp2a/com.android.internal.camera.flags/metadata_resize_fix_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.internal.camera.flags"
  name: "metadata_resize_fix"
  state: ENABLED
  permission: READ_ONLY
}
