flag_value {
  package: "com.android.internal.camera.flags"
  name: "zoom_method"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.internal.camera.flags/zoom_method_flag_values.textproto : ENABLED
}
