flag_value {
  package: "android.companion"
  name: "perm_sync_user_consent"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: companion
  # bug: 309528663
  # description: Expose perm sync user consent API
  # trace: frameworks/base/core/java/android/companion/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.companion/perm_sync_user_consent_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.companion/perm_sync_user_consent_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.companion/perm_sync_user_consent_flag_values.textproto : ENABLED
}
