flag_value {
  package: "android.provider"
  name: "user_keys"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: privacy_infra_policy
  # bug: 290696572
  # description: This flag controls new E2EE contact keys API
  # trace: frameworks/base/core/java/android/provider/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.provider/user_keys_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.provider/user_keys_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.provider/user_keys_flag_values.textproto : ENABLED
}
