flag_value {
  package: "com.android.wifi.flags"
  name: "get_channel_width_api"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.wifi.flags/get_channel_width_api_flag_values.textproto : ENABLED
}
