flag_value {
  package: "com.android.wifi.flags"
  name: "multiple_mld_on_sap_supported"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.wifi.flags/multiple_mld_on_sap_supported_flag_values.textproto : ENABLED
}
