flag_value {
  package: "com.android.wifi.flags"
  name: "wifi_direct_r2"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.wifi.flags/wifi_direct_r2_flag_values.textproto : ENABLED
}
