flag_value {
  package: "android.app"
  name: "app_start_info_cleanup_old_records"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: system_performance
  # purpose: PURPOSE_BUGFIX
  # bug: 384539178
  # description: Cleanup old records to reduce size of in memory store.
  # trace: frameworks/base/core/java/android/app/activity_manager.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/android.app/app_start_info_cleanup_old_records_flag_values.textproto : ENABLED
}
