flag_value {
  package: "android.app"
  name: "get_binding_uid_importance"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: backstage_power
  # bug: 292533010
  # description: API to get importance of UID that's binding to the caller
  # trace: frameworks/base/core/java/android/app/activity_manager.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.app/get_binding_uid_importance_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.app/get_binding_uid_importance_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.app/get_binding_uid_importance_flag_values.textproto : ENABLED
}
