flag_value {
  package: "android.app"
  name: "notifications_redesign_templates"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: systemui
  # bug: 378660052
  # description: Notifications Redesign: Update notification templates
  # trace: frameworks/base/core/java/android/app/notification.aconfig : DISABLED
  # trace: build/release/aconfig/bp3a/android.app/notifications_redesign_templates_flag_values.textproto : ENABLED
}
