flag_value {
  package: "android.app"
  name: "system_terms_of_address_enabled"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: globalintl
  # bug: 297798866
  # description: Feature flag for System Terms of Address
  # trace: frameworks/base/core/java/android/app/grammatical_inflection_manager.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.app/system_terms_of_address_enabled_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.app/system_terms_of_address_enabled_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.app/system_terms_of_address_enabled_flag_values.textproto : ENABLED
}
