flag_value {
  package: "android.app"
  name: "use_app_info_not_launched"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: backstage_power
  # purpose: PURPOSE_BUGFIX
  # bug: 362516211
  # description: Use the notLaunched state from ApplicationInfo instead of current value
  # trace: frameworks/base/core/java/android/app/activity_manager.aconfig : DISABLED
  # trace: build/release/aconfig/ap4a/android.app/use_app_info_not_launched_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.app/use_app_info_not_launched_flag_values.textproto : ENABLED
}
