flag_value {
  package: "android.provider.flags"
  name: "new_storage_public_api"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.configinfrastructure
  # namespace: core_experiments_team_internal
  # bug: 367765164
  # description: API flag for accessing new storage
  # trace: packages/modules/ConfigInfrastructure/framework/flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/android.provider.flags/new_storage_public_api_flag_values.textproto : ENABLED
}
