flag_value {
  package: "com.android.media.projection.flags"
  name: "media_projection_connected_display"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.media.projection.flags/media_projection_connected_display_flag_values.textproto : ENABLED
}
