flag_value {
  package: "android.app.jank"
  name: "detailed_app_jank_metrics_api"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: system_performance
  # bug: 366264614
  # description: Control the API portion of Detailed Application Jank Metrics
  # trace: frameworks/base/core/java/android/app/jank/flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/android.app.jank/detailed_app_jank_metrics_api_flag_values.textproto : ENABLED
}
