flag_value {
  package: "com.android.net.thread.flags"
  name: "channel_max_powers_enabled"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.tethering
  # namespace: thread_network
  # bug: 346686506
  # description: Controls whether the Android Thread setting max power of channel feature is enabled
  # trace: packages/modules/Connectivity/common/thread_flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.net.thread.flags/channel_max_powers_enabled_flag_values.textproto : ENABLED
}
