# build/release/aconfig/bp2a/com.android.libcore.readonly/post_cleanup_apis_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.libcore.readonly"
  name: "post_cleanup_apis"
  state: ENABLED
  permission: READ_ONLY
}
