flag_value {
  package: "android.service.autofill"
  name: "add_accessibility_title_for_augmented_autofill_dropdown"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/android.service.autofill/add_accessibility_title_for_augmented_autofill_dropdown_flag_values.textproto : ENABLED
}
