# build/release/aconfig/bp2a/android.service.autofill/autofill_w_metrics_flag_values.textproto : ENABLED
flag_value {
  package: "android.service.autofill"
  name: "autofill_w_metrics"
  state: ENABLED
  permission: READ_ONLY
}
