# build/release/aconfig/bp2a/android.service.autofill/autofill_session_destroyed_flag_values.textproto : ENABLED
flag_value {
  package: "android.service.autofill"
  name: "autofill_session_destroyed"
  state: ENABLED
  permission: READ_ONLY
}
