# build/release/aconfig/bp2a/android.service.autofill/multiple_fill_history_flag_values.textproto : ENABLED
flag_value {
  package: "android.service.autofill"
  name: "multiple_fill_history"
  state: ENABLED
  permission: READ_ONLY
}
