flag_value {
  package: "android.server"
  name: "allow_removing_vpn_service"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: wear_frameworks
  # bug: 340928692
  # description: Allow removing VpnManagerService
  # trace: frameworks/base/services/java/com/android/server/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap4a/android.server/allow_removing_vpn_service_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.server/allow_removing_vpn_service_flag_values.textproto : ENABLED
}
