# build/release/aconfig/bp2a/com.android.server.usage/screen_time_bypass_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.server.usage"
  name: "screen_time_bypass"
  state: ENABLED
  permission: READ_ONLY
}
