flag_value {
  package: "com.android.settings.flags"
  name: "catalyst_screen_timeout_25q3"
  state: ENABLED
  permission: READ_ONLY
  # container: system_ext
  # namespace: android_settings
  # bug: 352179685
  # description: Flag for Screen Timeout settings in 25Q3
  # trace: packages/apps/Settings/aconfig/catalyst/display.aconfig : DISABLED
  # trace: build/release/aconfig/bp3a/com.android.settings.flags/catalyst_screen_timeout_25q3_flag_values.textproto : ENABLED
}
