flag_value {
  package: "com.android.settings.flags"
  name: "catalyst_screen_timeout"
  state: ENABLED
  permission: READ_ONLY
  # container: system_ext
  # namespace: android_settings
  # bug: 323791114
  # description: Flag for Screen Timeout settings
  # trace: packages/apps/Settings/aconfig/catalyst/display.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.settings.flags/catalyst_screen_timeout_flag_values.textproto : ENABLED
}
