flag_value {
  package: "com.android.settings.flags"
  name: "catalyst_network_provider_and_internet_screen"
  state: ENABLED
  permission: READ_ONLY
  # container: system_ext
  # namespace: android_settings
  # bug: 323791114
  # description: Flag for Network & Internet
  # trace: packages/apps/Settings/aconfig/catalyst/network_and_internet.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.settings.flags/catalyst_network_provider_and_internet_screen_flag_values.textproto : ENABLED
}
