flag_value {
  package: "com.android.settings.flags"
  name: "sfps_enroll_refinement"
  state: ENABLED
  permission: READ_ONLY
  # container: system_ext
  # namespace: biometrics_integration
  # bug: 288155127
  # description: This flag controls whether the sfps pause enrollment feature should be enabled
  # trace: packages/apps/Settings/aconfig/settings_biometrics_integration_declarations.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.settings.flags/sfps_enroll_refinement_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.settings.flags/sfps_enroll_refinement_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.settings.flags/sfps_enroll_refinement_flag_values.textproto : ENABLED
}
