# build/release/aconfig/bp2a/android.hardware.devicestate.feature.flags/device_state_rdm_v2_flag_values.textproto : ENABLED
flag_value {
  package: "android.hardware.devicestate.feature.flags"
  name: "device_state_rdm_v2"
  state: ENABLED
  permission: READ_ONLY
}
