flag_value {
  package: "com.android.media.aaudio"
  name: "sample_rate_conversion"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: media_audio
  # bug: 219533889
  # description: Enable the AAudio sample rate converter.
  # trace: frameworks/av/media/audio/aconfig/aaudio.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.media.aaudio/sample_rate_conversion_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.media.aaudio/sample_rate_conversion_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.media.aaudio/sample_rate_conversion_flag_values.textproto : ENABLED
}
