# build/release/aconfig/bp2a/com.android.media.audioserver/power_stats_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.media.audioserver"
  name: "power_stats"
  state: ENABLED
  permission: READ_ONLY
}
