flag_value {
  package: "com.google.android.apps.nexuslauncher"
  name: "psb_aim_reskin"
  state: ENABLED
  permission: READ_ONLY
  # container: system_ext
  # namespace: launcher_search
  # purpose: PURPOSE_BUGFIX
  # bug: 413719316
  # description: Change the psb to containment version when AIM is available.
  # trace: vendor/unbundled_google/packages/NexusLauncher/aconfig/launcher_search.aconfig : DISABLED
  # trace: vendor/google/release/aconfig/bp3a/com.google.android.apps.nexuslauncher/psb_aim_reskin_flag_values.textproto : ENABLED
}
