# build/release/aconfig/bp2a/android.view.accessibility/a11y_expansion_state_api_flag_values.textproto : ENABLED
flag_value {
  package: "android.view.accessibility"
  name: "a11y_expansion_state_api"
  state: ENABLED
  permission: READ_ONLY
}
