# build/release/aconfig/bp2a/android.view.accessibility/deprecate_ani_label_for_apis_flag_values.textproto : ENABLED
flag_value {
  package: "android.view.accessibility"
  name: "deprecate_ani_label_for_apis"
  state: ENABLED
  permission: READ_ONLY
}
