# build/release/aconfig/bp2a/android.view.accessibility/support_multiple_labeledby_flag_values.textproto : ENABLED
flag_value {
  package: "android.view.accessibility"
  name: "support_multiple_labeledby"
  state: ENABLED
  permission: READ_ONLY
}
