# build/release/aconfig/bp2a/android.view.accessibility/supplemental_description_flag_values.textproto : ENABLED
flag_value {
  package: "android.view.accessibility"
  name: "supplemental_description"
  state: ENABLED
  permission: READ_ONLY
}
