# build/release/aconfig/bp2a/android.view.accessibility/tri_state_checked_flag_values.textproto : ENABLED
flag_value {
  package: "android.view.accessibility"
  name: "tri_state_checked"
  state: ENABLED
  permission: READ_ONLY
}
