flag_value {
  package: "com.android.settings.flags"
  name: "enroll_layout_truncate_improvement"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.settings.flags/enroll_layout_truncate_improvement_flag_values.textproto : ENABLED
}
