# build/release/aconfig/bp2a/android.view.inputmethod/ime_switcher_revamp_api_flag_values.textproto : ENABLED
flag_value {
  package: "android.view.inputmethod"
  name: "ime_switcher_revamp_api"
  state: ENABLED
  permission: READ_ONLY
}
