flag_value {
  package: "android.hardware.devicestate.feature.flags"
  name: "device_state_property_migration"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: windowing_sdk
  # bug: 336640888
  # description: Client migration to updated DeviceStateManager API's
  # trace: frameworks/base/core/java/android/hardware/devicestate/feature/flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp1a/android.hardware.devicestate.feature.flags/device_state_property_migration_flag_values.textproto : ENABLED
}
