flag_value {
  package: "com.android.server.power.optimization"
  name: "battery_stats_screen_state_event"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.server.power.optimization/battery_stats_screen_state_event_flag_values.textproto : ENABLED
}
