# vendor/google/release/aconfig/bp2a/android.uprobestats.flags/enable_uprobestats_flag_values.textproto : ENABLED
flag_value {
  package: "android.uprobestats.flags"
  name: "enable_uprobestats"
  state: ENABLED
  permission: READ_ONLY
}
