# vendor/google/release/aconfig/bp2a/android.uprobestats.flags/uprobestats_support_update_device_idle_temp_allowlist_flag_values.textproto : ENABLED
flag_value {
  package: "android.uprobestats.flags"
  name: "uprobestats_support_update_device_idle_temp_allowlist"
  state: ENABLED
  permission: READ_ONLY
}
