flag_value {
  package: "com.android.providers.settings"
  name: "load_apex_aconfig_protobufs"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: core_experiments_team_internal
  # bug: 327383546
  # description: When enabled, loads aconfig default values in apex flag protobufs into DeviceConfig on boot.
  # trace: frameworks/base/packages/SettingsProvider/src/com/android/providers/settings/device_config_service.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.providers.settings/load_apex_aconfig_protobufs_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.providers.settings/load_apex_aconfig_protobufs_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.providers.settings/load_apex_aconfig_protobufs_flag_values.textproto : ENABLED
}
