flag_value {
  package: "com.android.providers.settings"
  name: "notify_individual_aconfig_sysprop_changed"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: core_experiments_team_internal
  # purpose: PURPOSE_BUGFIX
  # bug: 331963764
  # description: When enabled, propagate individual aconfig sys props on flag stage.
  # trace: frameworks/base/packages/SettingsProvider/src/com/android/providers/settings/device_config_service.aconfig : DISABLED
  # trace: build/release/aconfig/ap4a/com.android.providers.settings/notify_individual_aconfig_sysprop_changed_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.providers.settings/notify_individual_aconfig_sysprop_changed_flag_values.textproto : ENABLED
}
