# build/release/aconfig/bp2a/com.android.hardware.input/enable_new_25q2_keycodes_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.hardware.input"
  name: "enable_new_25q2_keycodes"
  state: ENABLED
  permission: READ_ONLY
}
