# build/release/aconfig/bp2a/com.android.hardware.input/input_manager_lifecycle_support_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.hardware.input"
  name: "input_manager_lifecycle_support"
  state: ENABLED
  permission: READ_ONLY
}
