# build/release/aconfig/bp2a/com.android.hardware.input/manage_key_gestures_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.hardware.input"
  name: "manage_key_gestures"
  state: ENABLED
  permission: READ_ONLY
}
