# build/release/aconfig/bp2a/com.android.hardware.input/touchpad_visualizer_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.hardware.input"
  name: "touchpad_visualizer"
  state: ENABLED
  permission: READ_ONLY
}
