flag_value {
  package: "com.android.hardware.input"
  name: "use_key_gesture_event_handler"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.hardware.input/use_key_gesture_event_handler_flag_values.textproto : ENABLED
}
