# build/release/aconfig/bp2a/android.app/enable_tv_implicit_enter_pip_restriction_flag_values.textproto : ENABLED
flag_value {
  package: "android.app"
  name: "enable_tv_implicit_enter_pip_restriction"
  state: ENABLED
  permission: READ_ONLY
}
