# build/release/aconfig/bp2a/android.app/fix_wallpaper_changed_flag_values.textproto : ENABLED
flag_value {
  package: "android.app"
  name: "fix_wallpaper_changed"
  state: ENABLED
  permission: READ_ONLY
}
