# build/release/aconfig/bp2a/android.app/live_wallpaper_content_handling_flag_values.textproto : ENABLED
flag_value {
  package: "android.app"
  name: "live_wallpaper_content_handling"
  state: ENABLED
  permission: READ_ONLY
}
