flag_value {
  package: "android.app"
  name: "pic_isolate_cache_by_uid"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/android.app/pic_isolate_cache_by_uid_flag_values.textproto : ENABLED
}
