# build/release/aconfig/bp2a/android.app/pic_separate_permission_notifications_flag_values.textproto : ENABLED
flag_value {
  package: "android.app"
  name: "pic_separate_permission_notifications"
  state: ENABLED
  permission: READ_ONLY
}
