# build/release/aconfig/bp2a/android.app/redaction_on_lockscreen_metrics_flag_values.textproto : ENABLED
flag_value {
  package: "android.app"
  name: "redaction_on_lockscreen_metrics"
  state: ENABLED
  permission: READ_ONLY
}
