flag_value {
  package: "android.app"
  name: "redact_sensitive_content_notifications_on_lockscreen"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/android.app/redact_sensitive_content_notifications_on_lockscreen_flag_values.textproto : ENABLED
}
