# build/release/aconfig/bp2a/android.app/remove_next_wallpaper_component_flag_values.textproto : ENABLED
flag_value {
  package: "android.app"
  name: "remove_next_wallpaper_component"
  state: ENABLED
  permission: READ_ONLY
}
