# build/release/aconfig/bp2a/android.app/uid_importance_listener_for_uids_flag_values.textproto : ENABLED
flag_value {
  package: "android.app"
  name: "uid_importance_listener_for_uids"
  state: ENABLED
  permission: READ_ONLY
}
