flag_value {
  package: "android.permission.flags"
  name: "appop_mode_caching_enabled"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/android.permission.flags/appop_mode_caching_enabled_flag_values.textproto : ENABLED
}
