# build/release/aconfig/bp2a/android.permission.flags/supervision_role_permission_update_enabled_flag_values.textproto : ENABLED
flag_value {
  package: "android.permission.flags"
  name: "supervision_role_permission_update_enabled"
  state: ENABLED
  permission: READ_ONLY
}
