# build/release/aconfig/bp2a/android.permission.flags/use_profile_labels_for_default_app_section_titles_flag_values.textproto : ENABLED
flag_value {
  package: "android.permission.flags"
  name: "use_profile_labels_for_default_app_section_titles"
  state: ENABLED
  permission: READ_ONLY
}
