# build/release/aconfig/bp2a/android.permission.flags/wallet_role_icon_property_enabled_flag_values.textproto : ENABLED
flag_value {
  package: "android.permission.flags"
  name: "wallet_role_icon_property_enabled"
  state: ENABLED
  permission: READ_ONLY
}
