flag_value {
  package: "com.google.wear.sdk"
  name: "wear_api_version"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: wear_frameworks
  # bug: 304850686
  # description: Flag to enable the Wear API version abstraction.
  # trace: vendor/google_clockwork/sdk/lib/flags/wear_sdk_flags.aconfig : DISABLED
  # trace: vendor/google/release/aconfig/ap3a/com.google.wear.sdk/wear_api_version_flag_values.textproto : ENABLED
}
