flag_value {
  package: "com.android.media.codec.flags"
  name: "aidl_hal"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: codec_fwk
  # bug: 251850069
  # description: Feature flags for enabling AIDL HAL handling
  # trace: frameworks/av/media/aconfig/mediacodec_flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.media.codec.flags/aidl_hal_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.media.codec.flags/aidl_hal_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.media.codec.flags/aidl_hal_flag_values.textproto : ENABLED
}
