# build/release/aconfig/bp2a/com.android.window.flags/condense_configuration_change_for_simple_mode_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.window.flags"
  name: "condense_configuration_change_for_simple_mode"
  state: ENABLED
  permission: READ_ONLY
}
