# build/release/aconfig/bp2a/com.android.window.flags/enable_camera_compat_for_desktop_windowing_opt_out_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.window.flags"
  name: "enable_camera_compat_for_desktop_windowing_opt_out"
  state: ENABLED
  permission: READ_ONLY
}
