# build/release/aconfig/bp2a/com.android.window.flags/enable_drag_resize_set_up_in_bg_thread_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.window.flags"
  name: "enable_drag_resize_set_up_in_bg_thread"
  state: ENABLED
  permission: READ_ONLY
}
