flag_value {
  package: "com.android.window.flags"
  name: "enable_desktop_windowing_scvh_cache_bug_fix"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.window.flags/enable_desktop_windowing_scvh_cache_bug_fix_flag_values.textproto : ENABLED
}
