# build/release/aconfig/bp2a/com.android.window.flags/enable_window_context_resources_update_on_config_change_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.window.flags"
  name: "enable_window_context_resources_update_on_config_change"
  state: ENABLED
  permission: READ_ONLY
}
