flag_value {
  package: "com.android.window.flags"
  name: "exclude_drawing_app_theme_snapshot_from_lock"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.window.flags/exclude_drawing_app_theme_snapshot_from_lock_flag_values.textproto : ENABLED
}
