# build/release/aconfig/bp2a/com.android.window.flags/predictive_back_system_override_callback_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.window.flags"
  name: "predictive_back_system_override_callback"
  state: ENABLED
  permission: READ_ONLY
}
