# build/release/aconfig/bp2a/com.android.window.flags/reduce_keyguard_transitions_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.window.flags"
  name: "reduce_keyguard_transitions"
  state: ENABLED
  permission: READ_ONLY
}
