flag_value {
  package: "com.android.window.flags"
  name: "release_user_aspect_ratio_wm"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.window.flags/release_user_aspect_ratio_wm_flag_values.textproto : ENABLED
}
