# build/release/aconfig/bp2a/com.android.window.flags/wlinfo_oncreate_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.window.flags"
  name: "wlinfo_oncreate"
  state: ENABLED
  permission: READ_ONLY
}
