flag_value {
  package: "android.service.notification"
  name: "redact_sensitive_notifications_from_untrusted_listeners"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: systemui
  # bug: 306271190
  # description: This flag controls the redacting of sensitive notifications from untrusted NotificationListenerServices
  # trace: frameworks/base/core/java/android/service/notification/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.service.notification/redact_sensitive_notifications_from_untrusted_listeners_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.service.notification/redact_sensitive_notifications_from_untrusted_listeners_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.service.notification/redact_sensitive_notifications_from_untrusted_listeners_flag_values.textproto : ENABLED
}
