# build/release/aconfig/bp2a/com.android.intentresolver/fix_shortcuts_flashing_fixed_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.intentresolver"
  name: "fix_shortcuts_flashing_fixed"
  state: ENABLED
  permission: READ_ONLY
}
