flag_value {
  package: "android.hardware.usb.flags"
  name: "enable_is_mode_change_supported_api"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: usb
  # bug: 323470419
  # description: Feature flag for the api to check if a port supports mode change
  # trace: frameworks/base/core/java/android/hardware/usb/flags/usb_framework_flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.hardware.usb.flags/enable_is_mode_change_supported_api_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.hardware.usb.flags/enable_is_mode_change_supported_api_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.hardware.usb.flags/enable_is_mode_change_supported_api_flag_values.textproto : ENABLED
}
