flag_value {
  package: "android.app.admin.flags"
  name: "dedicated_device_control_api_enabled"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: enterprise
  # bug: 281964214
  # description: (API) Allow the device management role holder to control which platform features are available on dedicated devices.
  # trace: frameworks/base/core/java/android/app/admin/flags/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.app.admin.flags/dedicated_device_control_api_enabled_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.app.admin.flags/dedicated_device_control_api_enabled_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.app.admin.flags/dedicated_device_control_api_enabled_flag_values.textproto : ENABLED
}
