flag_value {
  package: "android.app.admin.flags"
  name: "device_policy_size_tracking_enabled"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: enterprise
  # bug: 281543351
  # description: Add feature to track the total policy size and have a max threshold - public API changes
  # trace: frameworks/base/core/java/android/app/admin/flags/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.app.admin.flags/device_policy_size_tracking_enabled_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.app.admin.flags/device_policy_size_tracking_enabled_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.app.admin.flags/device_policy_size_tracking_enabled_flag_values.textproto : ENABLED
}
