flag_value {
  package: "android.app.admin.flags"
  name: "onboarding_bugreport_v2_enabled"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: enterprise
  # bug: 302517677
  # description: Add feature to track required changes for enabled V2 of auto-capturing of onboarding bug reports.
  # trace: frameworks/base/core/java/android/app/admin/flags/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.app.admin.flags/onboarding_bugreport_v2_enabled_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.app.admin.flags/onboarding_bugreport_v2_enabled_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.app.admin.flags/onboarding_bugreport_v2_enabled_flag_values.textproto : ENABLED
}
