flag_value {
  package: "android.app.admin.flags"
  name: "policy_engine_migration_v2_enabled"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: enterprise
  # bug: 289520697
  # description: V2 of the policy engine migrations for Android V
  # trace: frameworks/base/core/java/android/app/admin/flags/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.app.admin.flags/policy_engine_migration_v2_enabled_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.app.admin.flags/policy_engine_migration_v2_enabled_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.app.admin.flags/policy_engine_migration_v2_enabled_flag_values.textproto : ENABLED
}
