flag_value {
  package: "android.app.admin.flags"
  name: "provisioning_context_parameter"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: enterprise
  # purpose: PURPOSE_BUGFIX
  # bug: 326525847
  # description: Add provisioningContext to store metadata about when the admin was set
  # trace: frameworks/base/core/java/android/app/admin/flags/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap4a/android.app.admin.flags/provisioning_context_parameter_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.app.admin.flags/provisioning_context_parameter_flag_values.textproto : ENABLED
}
