flag_value {
  package: "android.app.admin.flags"
  name: "quiet_mode_credential_bug_fix"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: enterprise
  # bug: 293441361
  # description: Guards a bugfix that ends the credential input flow if the managed user has not stopped.
  # trace: frameworks/base/core/java/android/app/admin/flags/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.app.admin.flags/quiet_mode_credential_bug_fix_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.app.admin.flags/quiet_mode_credential_bug_fix_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.app.admin.flags/quiet_mode_credential_bug_fix_flag_values.textproto : ENABLED
}
