flag_value {
  package: "android.content.pm"
  name: "provide_info_of_apk_in_apex"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: package_manager_service
  # bug: 306329516
  # description: Feature flag to provide the information of APK-in-APEX
  # trace: frameworks/base/core/java/android/content/pm/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.content.pm/provide_info_of_apk_in_apex_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.content.pm/provide_info_of_apk_in_apex_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.content.pm/provide_info_of_apk_in_apex_flag_values.textproto : ENABLED
}
