flag_value {
  package: "android.content.pm"
  name: "read_install_info"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: package_manager_service
  # bug: 275658500
  # description: Feature flag to read install related information from an APK.
  # trace: frameworks/base/core/java/android/content/pm/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.content.pm/read_install_info_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.content.pm/read_install_info_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.content.pm/read_install_info_flag_values.textproto : ENABLED
}
