flag_value {
  package: "android.content.pm"
  name: "recoverability_detection"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: package_manager_service
  # bug: 291135724
  # description: Feature flag to enable recoverability detection feature. It includes GMS core rollback and improvements to rescue party.
  # trace: frameworks/base/core/java/android/content/pm/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.content.pm/recoverability_detection_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.content.pm/recoverability_detection_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.content.pm/recoverability_detection_flag_values.textproto : ENABLED
}
