flag_value {
  package: "android.content.pm"
  name: "stay_stopped"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: backstage_power
  # bug: 296644915
  # description: Feature flag to improve stopped state enforcement
  # trace: frameworks/base/core/java/android/content/pm/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.content.pm/stay_stopped_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.content.pm/stay_stopped_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.content.pm/stay_stopped_flag_values.textproto : ENABLED
}
