# build/release/aconfig/bp2a/android.database.sqlite/concurrent_open_helper_flag_values.textproto : ENABLED
flag_value {
  package: "android.database.sqlite"
  name: "concurrent_open_helper"
  state: ENABLED
  permission: READ_ONLY
}
