# build/release/aconfig/bp2a/android.database.sqlite/oneway_finalizer_close_fixed_flag_values.textproto : ENABLED
flag_value {
  package: "android.database.sqlite"
  name: "oneway_finalizer_close_fixed"
  state: ENABLED
  permission: READ_ONLY
}
