flag_value {
  package: "face.flags.policy"
  name: "enable_ae_face_roi"
  state: ENABLED
  permission: READ_ONLY
  # container: vendor
  # namespace: pixel_biometrics_face
  # bug: 329891484
  # description: Enables using AE face ROI estimation
  # trace: vendor/google/biometrics/face/tuscany/flags/flags.aconfig : DISABLED
  # trace: vendor/google/release/aconfig/ap4a/face.flags.policy/enable_ae_face_roi_flag_values.textproto : ENABLED
  # trace: vendor/google/release/aconfig/bp1a/face.flags.policy/enable_ae_face_roi_flag_values.textproto : ENABLED
}
