flag_value {
  package: "com.android.systemui.shared"
  name: "enable_lpp_assist_invocation_effect"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: systemui
  # purpose: PURPOSE_BUGFIX
  # bug: 396099245
  # description: Enables invocation effect on power button long press for launching assistant
  # trace: frameworks/libs/systemui/aconfig/systemui.aconfig : DISABLED
  # trace: build/release/aconfig/bp3a/com.android.systemui.shared/enable_lpp_assist_invocation_effect_flag_values.textproto : ENABLED
}
