flag_value {
  package: "com.android.systemui.shared"
  name: "smartspace_ui_update"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: systemui
  # bug: 389741821
  # description: Update Smartspace UI
  # trace: frameworks/libs/systemui/aconfig/systemui.aconfig : DISABLED
  # trace: build/release/aconfig/bp3a/com.android.systemui.shared/smartspace_ui_update_flag_values.textproto : ENABLED
}
