flag_value {
  package: "com.android.graphics.surfaceflinger.flags"
  name: "adpf_gpu_sf"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: game
  # bug: 284324521
  # description: Guards use of the sending ADPF GPU duration hint and load hints from SurfaceFlinger to Power HAL
  # trace: frameworks/native/services/surfaceflinger/surfaceflinger_flags_new.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.graphics.surfaceflinger.flags/adpf_gpu_sf_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.graphics.surfaceflinger.flags/adpf_gpu_sf_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.graphics.surfaceflinger.flags/adpf_gpu_sf_flag_values.textproto : ENABLED
}
