# build/release/aconfig/bp2a/android.content.pm/app_compat_option_16kb_flag_values.textproto : ENABLED
flag_value {
  package: "android.content.pm"
  name: "app_compat_option_16kb"
  state: ENABLED
  permission: READ_ONLY
}
