# build/release/aconfig/bp2a/android.content.pm/improve_install_freeze_flag_values.textproto : ENABLED
flag_value {
  package: "android.content.pm"
  name: "improve_install_freeze"
  state: ENABLED
  permission: READ_ONLY
}
