# build/release/aconfig/bp2a/android.content.pm/reduce_broadcasts_for_component_state_changes_flag_values.textproto : ENABLED
flag_value {
  package: "android.content.pm"
  name: "reduce_broadcasts_for_component_state_changes"
  state: ENABLED
  permission: READ_ONLY
}
