# build/release/aconfig/bp2a/android.content.pm/sdk_dependency_installer_flag_values.textproto : ENABLED
flag_value {
  package: "android.content.pm"
  name: "sdk_dependency_installer"
  state: ENABLED
  permission: READ_ONLY
}
