flag_value {
  package: "android.view.accessibility"
  name: "collection_info_item_counts"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: accessibility
  # bug: 302376158
  # description: Fields for total items and the number of important for accessibility items in a collection
  # trace: frameworks/base/core/java/android/view/accessibility/flags/accessibility_flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.view.accessibility/collection_info_item_counts_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.view.accessibility/collection_info_item_counts_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.view.accessibility/collection_info_item_counts_flag_values.textproto : ENABLED
}
