flag_value {
  package: "android.app.admin.flags"
  name: "active_admin_cleanup"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/android.app.admin.flags/active_admin_cleanup_flag_values.textproto : ENABLED
}
