# build/release/aconfig/bp2a/android.app.admin.flags/internal_log_event_listener_flag_values.textproto : ENABLED
flag_value {
  package: "android.app.admin.flags"
  name: "internal_log_event_listener"
  state: ENABLED
  permission: READ_ONLY
}
