# build/release/aconfig/bp2a/android.app.admin.flags/set_auto_time_enabled_coexistence_flag_values.textproto : ENABLED
flag_value {
  package: "android.app.admin.flags"
  name: "set_auto_time_enabled_coexistence"
  state: ENABLED
  permission: READ_ONLY
}
