# build/release/aconfig/bp2a/android.app.admin.flags/user_provisioning_same_state_flag_values.textproto : ENABLED
flag_value {
  package: "android.app.admin.flags"
  name: "user_provisioning_same_state"
  state: ENABLED
  permission: READ_ONLY
}
