# build/release/aconfig/bp2a/android.media.audio/feature_spatial_audio_headtracking_low_latency_flag_values.textproto : ENABLED
flag_value {
  package: "android.media.audio"
  name: "feature_spatial_audio_headtracking_low_latency"
  state: ENABLED
  permission: READ_ONLY
}
