# build/release/aconfig/bp2a/android.media.audio/iamf_definitions_api_flag_values.textproto : ENABLED
flag_value {
  package: "android.media.audio"
  name: "iamf_definitions_api"
  state: ENABLED
  permission: READ_ONLY
}
