# build/release/aconfig/bp2a/android.media.audio/routed_device_ids_flag_values.textproto : ENABLED
flag_value {
  package: "android.media.audio"
  name: "routed_device_ids"
  state: ENABLED
  permission: READ_ONLY
}
