# build/release/aconfig/bp2a/android.media.audio/speaker_layout_api_flag_values.textproto : ENABLED
flag_value {
  package: "android.media.audio"
  name: "speaker_layout_api"
  state: ENABLED
  permission: READ_ONLY
}
