# build/release/aconfig/bp2a/android.media.audio/speaker_cleanup_usage_flag_values.textproto : ENABLED
flag_value {
  package: "android.media.audio"
  name: "speaker_cleanup_usage"
  state: ENABLED
  permission: READ_ONLY
}
