flag_value {
  package: "com.android.adservices.flags"
  name: "adservices_enable_per_module_overrides_api"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.adservices.flags/adservices_enable_per_module_overrides_api_flag_values.textproto : ENABLED
}
