flag_value {
  package: "com.android.adservices.flags"
  name: "fledge_enable_custom_audience_component_ads"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.adservices.flags/fledge_enable_custom_audience_component_ads_flag_values.textproto : ENABLED
}
