flag_value {
  package: "com.android.adservices.flags"
  name: "sdksandbox_use_effective_target_sdk_version_for_restrictions"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.adservices.flags/sdksandbox_use_effective_target_sdk_version_for_restrictions_flag_values.textproto : ENABLED
}
