flag_value {
  package: "com.android.systemui"
  name: "clipboard_use_description_mimetype"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: systemui
  # purpose: PURPOSE_BUGFIX
  # bug: 357197236
  # description: Read item mimetype from description rather than checking URI
  # trace: frameworks/base/packages/SystemUI/aconfig/systemui.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.systemui/clipboard_use_description_mimetype_flag_values.textproto : ENABLED
}
