flag_value {
  package: "com.android.systemui"
  name: "contextual_tips_assistant_dismiss_fix"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: systemui
  # purpose: PURPOSE_BUGFIX
  # bug: 334759504
  # description: Improve assistant dismiss signal accuracy for contextual tips.
  # trace: frameworks/base/packages/SystemUI/aconfig/systemui.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.systemui/contextual_tips_assistant_dismiss_fix_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.systemui/contextual_tips_assistant_dismiss_fix_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.systemui/contextual_tips_assistant_dismiss_fix_flag_values.textproto : ENABLED
}
