flag_value {
  package: "com.android.systemui"
  name: "enable_background_keyguard_ondrawn_callback"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: systemui
  # purpose: PURPOSE_BUGFIX
  # bug: 295873557
  # description: Calls the onDrawn keyguard in the background, without being blocked by mainthread work. This results in the screen to turn on earlier when the main thread is stuck. Note that, even after this callback is called, we're waiting for all windows to finish  drawing.
  # trace: frameworks/base/packages/SystemUI/aconfig/systemui.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.systemui/enable_background_keyguard_ondrawn_callback_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.systemui/enable_background_keyguard_ondrawn_callback_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.systemui/enable_background_keyguard_ondrawn_callback_flag_values.textproto : ENABLED
}
