flag_value {
  package: "com.android.systemui"
  name: "floating_menu_notify_targets_changed_on_strict_diff"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: accessibility
  # purpose: PURPOSE_BUGFIX
  # bug: 376473165
  # description: Only notify listeners that the list of accessibility targets has changed if the lists are not identical.
  # trace: frameworks/base/packages/SystemUI/aconfig/accessibility.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.systemui/floating_menu_notify_targets_changed_on_strict_diff_flag_values.textproto : ENABLED
}
