flag_value {
  package: "com.android.systemui"
  name: "notifications_redesign_footer_view"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: systemui
  # bug: 375010573
  # description: Notifications Redesign: Update the look of the notifications footer.
  # trace: frameworks/base/packages/SystemUI/aconfig/systemui.aconfig : DISABLED
  # trace: build/release/aconfig/bp3a/com.android.systemui/notifications_redesign_footer_view_flag_values.textproto : ENABLED
}
