flag_value {
  package: "com.android.systemui"
  name: "notification_async_group_header_inflation"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: systemui
  # bug: 217799515
  # description: Inflates the notification group summary header views from the background thread.
  # trace: frameworks/base/packages/SystemUI/aconfig/systemui.aconfig : DISABLED
  # trace: build/release/aconfig/ap4a/com.android.systemui/notification_async_group_header_inflation_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.systemui/notification_async_group_header_inflation_flag_values.textproto : ENABLED
}
