flag_value {
  package: "com.android.systemui"
  name: "notify_password_text_view_user_activity_in_background"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: systemui
  # purpose: PURPOSE_BUGFIX
  # bug: 346882515
  # description: Decide whether to notify the user activity in password text view, to power manager in the background thread.
  # trace: frameworks/base/packages/SystemUI/aconfig/systemui.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.systemui/notify_password_text_view_user_activity_in_background_flag_values.textproto : ENABLED
}
