flag_value {
  package: "com.android.systemui"
  name: "notification_shade_blur"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: systemui
  # bug: 370555223
  # description: Enables the new blur effect on the Notification Shade.
  # trace: frameworks/base/packages/SystemUI/aconfig/systemui.aconfig : DISABLED
  # trace: build/release/aconfig/bp3a/com.android.systemui/notification_shade_blur_flag_values.textproto : ENABLED
}
