flag_value {
  package: "com.android.systemui"
  name: "notification_avalanche_suppression"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: systemui
  # bug: 321089634
  # description: After notification avalanche floodgate event, suppress HUNs completely.
  # trace: frameworks/base/packages/SystemUI/aconfig/systemui.aconfig : DISABLED
  # trace: build/release/aconfig/bp1a/com.android.systemui/notification_avalanche_suppression_flag_values.textproto : ENABLED
}
