flag_value {
  package: "com.android.systemui"
  name: "notifications_footer_visibility_fix"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: systemui
  # purpose: PURPOSE_BUGFIX
  # bug: 356552869
  # description: Fixes a bug where the footer would briefly appear when dismissing a HUN
  # trace: frameworks/base/packages/SystemUI/aconfig/systemui.aconfig : DISABLED
  # trace: build/release/aconfig/bp1a/com.android.systemui/notifications_footer_visibility_fix_flag_values.textproto : ENABLED
}
