flag_value {
  package: "com.android.systemui"
  name: "pin_input_field_styled_focus_state"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: systemui
  # bug: 316106516
  # description: Enables styled focus states on pin input field if keyboard is connected
  # trace: frameworks/base/packages/SystemUI/aconfig/systemui.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.systemui/pin_input_field_styled_focus_state_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.systemui/pin_input_field_styled_focus_state_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.systemui/pin_input_field_styled_focus_state_flag_values.textproto : ENABLED
}
