flag_value {
  package: "com.android.systemui"
  name: "qs_tile_focus_state"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: systemui
  # bug: 312899524
  # description: enables new focus outline for qs tiles when focused on with physical keyboard
  # trace: frameworks/base/packages/SystemUI/aconfig/systemui.aconfig : DISABLED
  # trace: build/release/aconfig/ap4a/com.android.systemui/qs_tile_focus_state_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.systemui/qs_tile_focus_state_flag_values.textproto : ENABLED
}
