flag_value {
  package: "com.android.systemui"
  name: "register_wallpaper_notifier_background"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: systemui
  # purpose: PURPOSE_BUGFIX
  # bug: 327315860
  # description: Decide whether to register wallpaper change broadcast receiver on background executor.
  # trace: frameworks/base/packages/SystemUI/aconfig/systemui.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.systemui/register_wallpaper_notifier_background_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.systemui/register_wallpaper_notifier_background_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.systemui/register_wallpaper_notifier_background_flag_values.textproto : ENABLED
}
