flag_value {
  package: "com.android.systemui"
  name: "revamped_bouncer_messages"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: systemui
  # bug: 236891644
  # description: Change the bouncer message to be a 2-line more descriptive message
  # trace: frameworks/base/packages/SystemUI/aconfig/systemui.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.systemui/revamped_bouncer_messages_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.systemui/revamped_bouncer_messages_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.systemui/revamped_bouncer_messages_flag_values.textproto : ENABLED
}
