flag_value {
  package: "com.android.systemui"
  name: "save_and_restore_magnification_settings_buttons"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: accessibility
  # purpose: PURPOSE_BUGFIX
  # bug: 325567876
  # description: Saves the selected button status in magnification settings and restore the status when revisiting the same smallest screen DP.
  # trace: frameworks/base/packages/SystemUI/aconfig/accessibility.aconfig : DISABLED
  # trace: build/release/aconfig/ap4a/com.android.systemui/save_and_restore_magnification_settings_buttons_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.systemui/save_and_restore_magnification_settings_buttons_flag_values.textproto : ENABLED
}
