flag_value {
  package: "com.android.systemui"
  name: "settings_ext_register_content_observer_on_bg_thread"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: systemui
  # purpose: PURPOSE_BUGFIX
  # bug: 355389014
  # description: Register content observer in callback flow APIs on background thread in SettingsProxyExt.
  # trace: frameworks/base/packages/SystemUI/aconfig/systemui.aconfig : DISABLED
  # trace: build/release/aconfig/ap4a/com.android.systemui/settings_ext_register_content_observer_on_bg_thread_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.systemui/settings_ext_register_content_observer_on_bg_thread_flag_values.textproto : ENABLED
}
