flag_value {
  package: "com.android.systemui"
  name: "spatial_model_app_pushback"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: systemui
  # bug: 370560660
  # description: Implement the depth push scaling effect on the current app when users pull down shade.
  # trace: frameworks/base/packages/SystemUI/aconfig/systemui.aconfig : DISABLED
  # trace: build/release/aconfig/bp3a/com.android.systemui/spatial_model_app_pushback_flag_values.textproto : ENABLED
}
