flag_value {
  package: "com.android.systemui"
  name: "stabilize_heads_up_group_v2"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: systemui
  # purpose: PURPOSE_BUGFIX
  # bug: 357753857
  # description: Stabilize heads up groups in VisualStabilityCoordinator
  # trace: frameworks/base/packages/SystemUI/aconfig/systemui.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.systemui/stabilize_heads_up_group_v2_flag_values.textproto : ENABLED
}
