flag_value {
  package: "com.android.systemui"
  name: "visual_interruptions_refactor"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: systemui
  # bug: 261728888
  # description: Enables the refactored version of the code to decide when notifications HUN, bubble, pulse, or FSI.
  # trace: frameworks/base/packages/SystemUI/aconfig/systemui.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.systemui/visual_interruptions_refactor_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.systemui/visual_interruptions_refactor_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.systemui/visual_interruptions_refactor_flag_values.textproto : ENABLED
}
