flag_value {
  package: "com.google.android.settings.flags"
  name: "safe_boot_policy_enabled"
  state: ENABLED
  permission: READ_ONLY
  # container: system_ext
  # namespace: repair_mode
  # bug: 329454522
  # description: This flag controls whether to show Repair Mode menus according to safe boot policy
  # trace: vendor/unbundled_google/packages/SettingsGoogle/aconfig/settings_repair_mode_flag_declarations.aconfig : DISABLED
  # trace: vendor/google/release/aconfig/ap3a/com.google.android.settings.flags/safe_boot_policy_enabled_flag_values.textproto : ENABLED
  # trace: vendor/google/release/aconfig/ap4a/com.google.android.settings.flags/safe_boot_policy_enabled_flag_values.textproto : ENABLED
  # trace: vendor/google/release/aconfig/bp1a/com.google.android.settings.flags/safe_boot_policy_enabled_flag_values.textproto : ENABLED
}
