flag_value {
  package: "android.car.feature"
  name: "batched_subscriptions"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: car_framework
  # bug: 298257574
  # description: Controls whether to enable batched subscriptions for multiple [propId, areaId]s
  # trace: packages/services/Car/aconfig/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.car.feature/batched_subscriptions_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.car.feature/batched_subscriptions_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.car.feature/batched_subscriptions_flag_values.textproto : ENABLED
}
