flag_value {
  package: "android.car.feature"
  name: "car_property_value_property_status"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: car_framework
  # bug: 326109669
  # description: Enables use of new property status API
  # trace: packages/services/Car/aconfig/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.car.feature/car_property_value_property_status_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.car.feature/car_property_value_property_status_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.car.feature/car_property_value_property_status_flag_values.textproto : ENABLED
}
