flag_value {
  package: "android.car.feature"
  name: "car_evs_stream_management"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: car_framework
  # bug: 293810167
  # description: Allows clients to stop stream individually and identify the origin of delivered framebuffers from CarEvsBufferDescriptor
  # trace: packages/services/Car/aconfig/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.car.feature/car_evs_stream_management_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.car.feature/car_evs_stream_management_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.car.feature/car_evs_stream_management_flag_values.textproto : ENABLED
}
