flag_value {
  package: "android.car.feature"
  name: "package_manager_extensions_for_sdv"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: car_framework
  # bug: 344832846
  # description: Enables SDV to access packages manager functions
  # trace: packages/services/Car/aconfig/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap4a/android.car.feature/package_manager_extensions_for_sdv_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.car.feature/package_manager_extensions_for_sdv_flag_values.textproto : ENABLED
}
