flag_value {
  package: "android.car.feature"
  name: "persist_ap_settings"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: car_framework
  # bug: 301660611
  # description: Controls whether car persist ap settings can be configured
  # trace: packages/services/Car/aconfig/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.car.feature/persist_ap_settings_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.car.feature/persist_ap_settings_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.car.feature/persist_ap_settings_flag_values.textproto : ENABLED
}
