flag_value {
  package: "android.car.feature"
  name: "subscription_with_resolution"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: car_framework
  # bug: 276124296
  # description: Controls whether to round incoming property events to the resolution requested
  # trace: packages/services/Car/aconfig/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.car.feature/subscription_with_resolution_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.car.feature/subscription_with_resolution_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.car.feature/subscription_with_resolution_flag_values.textproto : ENABLED
}
