flag_value {
  package: "android.security"
  name: "extend_ecm_to_all_settings"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: responsible_apis
  # bug: 297372999
  # description: Allow all app settings to be restrictable via configuration
  # trace: frameworks/base/core/java/android/security/responsible_apis_flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.security/extend_ecm_to_all_settings_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.security/extend_ecm_to_all_settings_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.security/extend_ecm_to_all_settings_flag_values.textproto : ENABLED
}
