flag_value {
  package: "android.security"
  name: "frp_enforcement"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: hardware_backed_security
  # bug: 290312729
  # description: This flag controls whether PDB enforces FRP
  # trace: frameworks/base/core/java/android/security/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.security/frp_enforcement_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.security/frp_enforcement_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.security/frp_enforcement_flag_values.textproto : ENABLED
}
