flag_value {
  package: "android.security"
  name: "keystore_grant_api"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: hardware_backed_security
  # bug: 351158708
  # description: Feature flag for exposing KeyStore grant APIs
  # trace: frameworks/base/core/java/android/security/flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/android.security/keystore_grant_api_flag_values.textproto : ENABLED
}
