flag_value {
  package: "android.security"
  name: "mgf1_digest_setter_v2"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: hardware_backed_security
  # bug: 308378912
  # description: Feature flag for mgf1 digest setter in key generation and import parameters.
  # trace: frameworks/base/core/java/android/security/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.security/mgf1_digest_setter_v2_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.security/mgf1_digest_setter_v2_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.security/mgf1_digest_setter_v2_flag_values.textproto : ENABLED
}
