flag_value {
  package: "android.security"
  name: "protect_device_config_flags"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: psap_ai
  # bug: 364083026
  # description: Feature flag to limit adb shell to allowlisted flags
  # trace: frameworks/base/core/java/android/security/flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/android.security/protect_device_config_flags_flag_values.textproto : ENABLED
}
