# build/release/aconfig/bp2a/android.provider/system_regional_preferences_api_enabled_flag_values.textproto : ENABLED
flag_value {
  package: "android.provider"
  name: "system_regional_preferences_api_enabled"
  state: ENABLED
  permission: READ_ONLY
}
