flag_value {
  package: "android.service.dreams"
  name: "allow_dream_with_charge_limit"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: systemui
  # purpose: PURPOSE_BUGFIX
  # bug: 397717022
  # description: Allows dreaming even when a charge limit is active
  # trace: frameworks/base/core/java/android/service/dreams/flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp3a/android.service.dreams/allow_dream_with_charge_limit_flag_values.textproto : ENABLED
}
