flag_value {
  package: "com.android.media.projection.flags"
  name: "stop_media_projection_on_call_end"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: media_projection
  # bug: 368336349
  # description: Stops MediaProjection sessions when a call ends
  # trace: frameworks/base/media/java/android/media/flags/projection.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.media.projection.flags/stop_media_projection_on_call_end_flag_values.textproto : ENABLED
}
