flag_value {
  package: "android.graphics.pdf.flags"
  name: "enable_pdf_viewer"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.mediaprovider
  # namespace: pdf_viewer
  # bug: 319561098
  # description: This flag controls whether to enable pdf viewer APIs.
  # trace: packages/providers/MediaProvider/pdf/framework/pdf_viewer_flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.graphics.pdf.flags/enable_pdf_viewer_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.graphics.pdf.flags/enable_pdf_viewer_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.graphics.pdf.flags/enable_pdf_viewer_flag_values.textproto : ENABLED
}
