flag_value {
  package: "com.android.internal.jank"
  name: "ignore_hwui_is_first_frame"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.internal.jank/ignore_hwui_is_first_frame_flag_values.textproto : ENABLED
}
