flag_value {
  package: "com.android.server.notification"
  name: "refactor_attention_helper"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: systemui
  # bug: 291907312
  # description: This flag controls the refactoring of NMS to NotificationAttentionHelper
  # trace: frameworks/base/services/core/java/com/android/server/notification/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.server.notification/refactor_attention_helper_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.server.notification/refactor_attention_helper_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.server.notification/refactor_attention_helper_flag_values.textproto : ENABLED
}
