flag_value {
  package: "com.android.internal.camera.flags"
  name: "camera_extensions_characteristics_get"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: camera_platform
  # bug: 280649914
  # description: Enable get extension specific camera characteristics API
  # trace: frameworks/av/camera/camera_platform.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.internal.camera.flags/camera_extensions_characteristics_get_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.internal.camera.flags/camera_extensions_characteristics_get_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.internal.camera.flags/camera_extensions_characteristics_get_flag_values.textproto : ENABLED
}
