flag_value {
  package: "com.android.internal.camera.flags"
  name: "color_temperature"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: camera_platform
  # bug: 359409044
  # description: Add keys to manually set color temperature and color tint
  # trace: frameworks/av/camera/camera_platform.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.internal.camera.flags/color_temperature_flag_values.textproto : ENABLED
}
