flag_value {
  package: "com.android.internal.camera.flags"
  name: "inject_session_params"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: camera_platform
  # bug: 308984721
  # description: Enable session parameter injection via reconfiguration
  # trace: frameworks/av/camera/camera_platform.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.internal.camera.flags/inject_session_params_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.internal.camera.flags/inject_session_params_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.internal.camera.flags/inject_session_params_flag_values.textproto : ENABLED
}
