flag_value {
  package: "com.android.internal.camera.flags"
  name: "multiresolution_imagereader_usage_config"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: camera_platform
  # bug: 301588215
  # description: Enable creating MultiResolutionImageReader with usage flag configuration
  # trace: frameworks/av/camera/camera_platform.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.internal.camera.flags/multiresolution_imagereader_usage_config_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.internal.camera.flags/multiresolution_imagereader_usage_config_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.internal.camera.flags/multiresolution_imagereader_usage_config_flag_values.textproto : ENABLED
}
