flag_value {
  package: "com.android.internal.camera.flags"
  name: "zoom_method"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: camera_platform
  # bug: 350076823
  # description: Gives apps explicit control on reflects zoom via ZOOM_RATIO capture result
  # trace: frameworks/av/camera/camera_platform.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.internal.camera.flags/zoom_method_flag_values.textproto : ENABLED
}
