# build/release/aconfig/bp2a/com.android.server.power.hint/reset_on_fork_enabled_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.server.power.hint"
  name: "reset_on_fork_enabled"
  state: ENABLED
  permission: READ_ONLY
}
