flag_value {
  package: "android.view.flags"
  name: "enable_surface_native_alloc_registration_ro"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: toolkit
  # bug: 306193257
  # description: Feature flag for registering surfaces with the VM for faster cleanup. Fixed readonly version.
  # trace: frameworks/base/core/java/android/view/flags/view_flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.view.flags/enable_surface_native_alloc_registration_ro_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.view.flags/enable_surface_native_alloc_registration_ro_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.view.flags/enable_surface_native_alloc_registration_ro_flag_values.textproto : ENABLED
}
