flag_value {
  package: "com.android.aconfig_new_storage"
  name: "enable_aconfigd_from_mainline"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/com.android.aconfig_new_storage/enable_aconfigd_from_mainline_flag_values.textproto : ENABLED
}
