flag_value {
  package: "android.service.notification"
  name: "notification_force_grouping"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/android.service.notification/notification_force_grouping_flag_values.textproto : ENABLED
}
