# build/release/aconfig/bp2a/android.service.notification/notification_silent_flag_flag_values.textproto : ENABLED
flag_value {
  package: "android.service.notification"
  name: "notification_silent_flag"
  state: ENABLED
  permission: READ_ONLY
}
