flag_value {
  package: "com.android.server.accessibility"
  name: "package_monitor_dedicated_thread"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: accessibility
  # purpose: PURPOSE_BUGFIX
  # bug: 348138695
  # description: Runs the A11yManagerService PackageMonitor on a dedicated thread
  # trace: frameworks/base/services/accessibility/accessibility.aconfig : DISABLED
  # trace: build/release/aconfig/bp1a/com.android.server.accessibility/package_monitor_dedicated_thread_flag_values.textproto : ENABLED
}
