flag_value {
  package: "android.app.job"
  name: "ignore_important_while_foreground"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: backstage_power
  # bug: 374175032
  # description: Ignore the important_while_foreground flag and change the related APIs to be not effective
  # trace: frameworks/base/apex/jobscheduler/framework/aconfig/job.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/android.app.job/ignore_important_while_foreground_flag_values.textproto : ENABLED
}
