flag_value {
  package: "android.media.codec"
  name: "apv_support"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: codec_fwk
  # bug: 375464302
  # description: Feature flag for Android support for APV Content
  # trace: frameworks/av/media/aconfig/codec_fwk.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/android.media.codec/apv_support_flag_values.textproto : ENABLED
}
