flag_value {
  package: "android.media.codec"
  name: "codec_availability_support"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: codec_fwk
  # bug: 363282971
  # description: Feature flag for codec availability HAL API implementation
  # trace: frameworks/av/media/aconfig/codec_fwk.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/android.media.codec/codec_availability_support_flag_values.textproto : ENABLED
}
