flag_value {
  package: "android.media.codec"
  name: "input_surface_throttle"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: codec_fwk
  # purpose: PURPOSE_BUGFIX
  # bug: 342269852
  # description: Bugfix flag for input surface throttle
  # trace: frameworks/av/media/aconfig/codec_fwk.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.media.codec/input_surface_throttle_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.media.codec/input_surface_throttle_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.media.codec/input_surface_throttle_flag_values.textproto : ENABLED
}
