flag_value {
  package: "android.media.codec"
  name: "set_state_early"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: codec_fwk
  # purpose: PURPOSE_BUGFIX
  # bug: 298613712
  # description: Bugfix flag for setting state early to avoid a race condition
  # trace: frameworks/av/media/aconfig/codec_fwk.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.media.codec/set_state_early_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.media.codec/set_state_early_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.media.codec/set_state_early_flag_values.textproto : ENABLED
}
