flag_value {
  package: "com.android.server.job"
  name: "enforce_quota_policy_to_fgs_jobs"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: backstage_power
  # bug: 341201311
  # description: Applies the normal quota policy to FGS jobs
  # trace: frameworks/base/apex/jobscheduler/service/aconfig/job.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.server.job/enforce_quota_policy_to_fgs_jobs_flag_values.textproto : ENABLED
}
