flag_value {
  package: "com.android.server.job"
  name: "thermal_restrictions_to_fgs_jobs"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: backstage_power
  # purpose: PURPOSE_BUGFIX
  # bug: 315157163
  # description: Apply thermal restrictions to FGS jobs.
  # trace: frameworks/base/apex/jobscheduler/service/aconfig/job.aconfig : DISABLED
  # trace: build/release/aconfig/ap4a/com.android.server.job/thermal_restrictions_to_fgs_jobs_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.server.job/thermal_restrictions_to_fgs_jobs_flag_values.textproto : ENABLED
}
