flag_value {
  package: "android.permission.flags"
  name: "device_aware_permissions_enabled"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: permissions
  # bug: 274852670
  # description: When the flag is off no permissions can be device aware
  # trace: frameworks/base/core/java/android/permission/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.permission.flags/device_aware_permissions_enabled_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.permission.flags/device_aware_permissions_enabled_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.permission.flags/device_aware_permissions_enabled_flag_values.textproto : ENABLED
}
