flag_value {
  package: "android.permission.flags"
  name: "enable_otp_in_text_classifiers"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: permissions
  # bug: 351976749
  # description: Enables ExtServices to leverage TextClassifier for OTP detection
  # trace: frameworks/base/core/java/android/permission/flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/android.permission.flags/enable_otp_in_text_classifiers_flag_values.textproto : ENABLED
}
