flag_value {
  package: "android.permission.flags"
  name: "get_emergency_role_holder_api_enabled"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: permissions
  # bug: 323157319
  # description: Enables the getEmergencyRoleHolder API.
  # trace: frameworks/base/core/java/android/permission/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.permission.flags/get_emergency_role_holder_api_enabled_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.permission.flags/get_emergency_role_holder_api_enabled_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.permission.flags/get_emergency_role_holder_api_enabled_flag_values.textproto : ENABLED
}
