flag_value {
  package: "android.permission.flags"
  name: "replace_body_sensor_permission_enabled"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: android_health_services
  # bug: 364638912
  # description: Enables replacement of BODY_SENSORS/BODY_SENSORS_BACKGROUND permissions with granular health permissions READ_HEART_RATE, READ_SKIN_TEMPERATURE, READ_OXYGEN_SATURATION, and READ_HEALTH_DATA_IN_BACKGROUND
  # trace: frameworks/base/core/java/android/permission/flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/android.permission.flags/replace_body_sensor_permission_enabled_flag_values.textproto : ENABLED
}
