flag_value {
  package: "android.permission.flags"
  name: "signature_permission_allowlist_enabled"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: permissions
  # bug: 308573169
  # description: Enable signature permission allowlist
  # trace: frameworks/base/core/java/android/permission/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.permission.flags/signature_permission_allowlist_enabled_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.permission.flags/signature_permission_allowlist_enabled_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.permission.flags/signature_permission_allowlist_enabled_flag_values.textproto : ENABLED
}
