# build/release/aconfig/bp2a/android.view.flags/dynamic_view_rotary_haptics_configuration_flag_values.textproto : ENABLED
flag_value {
  package: "android.view.flags"
  name: "dynamic_view_rotary_haptics_configuration"
  state: ENABLED
  permission: READ_ONLY
}
