flag_value {
  package: "com.android.providers.media.flags"
  name: "audio_sample_columns"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.mediaprovider
  # namespace: mediaprovider
  # bug: 352523369
  # description: Controls exposure of bits_per_sample and samplerate audio columns
  # trace: packages/providers/MediaProvider/mediaprovider_flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.providers.media.flags/audio_sample_columns_flag_values.textproto : ENABLED
}
