flag_value {
  package: "com.android.providers.media.flags"
  name: "enable_unicode_check"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.mediaprovider
  # namespace: mediaprovider
  # bug: 263914218
  # description: This flag controls whether the unicode check is enabled
  # trace: packages/providers/MediaProvider/mediaprovider_flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.providers.media.flags/enable_unicode_check_flag_values.textproto : ENABLED
}
