flag_value {
  package: "com.android.providers.media.flags"
  name: "enable_stable_uris_for_external_primary_volume"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.mediaprovider
  # namespace: mediaprovider
  # bug: 213931581
  # description: This flag will enable stable uris for external primary volume
  # trace: packages/providers/MediaProvider/mediaprovider_flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.providers.media.flags/enable_stable_uris_for_external_primary_volume_flag_values.textproto : ENABLED
}
