flag_value {
  package: "com.android.providers.media.flags"
  name: "enable_photopicker_search"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.mediaprovider
  # namespace: mediaprovider
  # bug: 361026918
  # description: This flag controls whether to enable search feature in photopicker
  # trace: packages/providers/MediaProvider/mediaprovider_flags.aconfig : DISABLED
  # trace: vendor/google_shared/build/release/aconfig/mainline_2025_06/com.android.providers.media.flags/enable_photopicker_search_flag_values.textproto : ENABLED
}
