flag_value {
  package: "com.android.providers.media.flags"
  name: "enable_photopicker_transcoding"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.mediaprovider
  # namespace: mediaprovider
  # bug: 367886883
  # description: This flag controls whether to enable transcoding feature in photopicker
  # trace: packages/providers/MediaProvider/mediaprovider_flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.providers.media.flags/enable_photopicker_transcoding_flag_values.textproto : ENABLED
}
