flag_value {
  package: "com.android.providers.media.flags"
  name: "enable_mark_is_favorite_status_api"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.mediaprovider
  # namespace: mediaprovider
  # bug: 294364218
  # description: Enables mark media as favorite API
  # trace: packages/providers/MediaProvider/mediaprovider_flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.providers.media.flags/enable_mark_is_favorite_status_api_flag_values.textproto : ENABLED
}
