flag_value {
  package: "android.companion"
  name: "association_tag"
  state: ENABLED
  permission: READ_ONLY
  # vendor/google_shared/build/release/aconfig/bp2a/android.companion/association_tag_flag_values.textproto : ENABLED
}
