flag_value {
  package: "android.tracing"
  name: "perfetto_ime"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: windowing_tools
  # bug: 276433199
  # description: Migrate IME tracing to Perfetto
  # trace: frameworks/base/core/java/android/tracing/flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp1a/android.tracing/perfetto_ime_flag_values.textproto : ENABLED
}
