flag_value {
  package: "com.android.wifi.flags"
  name: "public_bands_for_lohs"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.wifi
  # namespace: wifi
  # bug: 362355566
  # description: Public bands api for local only hotspot from system api
  # trace: packages/modules/Wifi/flags/wifi_flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.wifi.flags/public_bands_for_lohs_flag_values.textproto : ENABLED
}
