flag_value {
  package: "com.android.wifi.flags"
  name: "shared_connectivity_broadcast_receiver_test_api"
  state: ENABLED
  permission: READ_ONLY
  # container: com.android.wifi
  # namespace: wifi
  # bug: 305067231
  # description: Control the test API for SharedConnectivityManager's getBroadcastReceiver() method
  # trace: packages/modules/Wifi/flags/wifi_flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.wifi.flags/shared_connectivity_broadcast_receiver_test_api_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.wifi.flags/shared_connectivity_broadcast_receiver_test_api_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.wifi.flags/shared_connectivity_broadcast_receiver_test_api_flag_values.textproto : ENABLED
}
