# build/release/aconfig/bp2a/com.android.nfc.flags/check_passed_in_package_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.nfc.flags"
  name: "check_passed_in_package"
  state: ENABLED
  permission: READ_ONLY
}
