# build/release/aconfig/bp2a/com.android.nfc.flags/coalesce_rf_events_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.nfc.flags"
  name: "coalesce_rf_events"
  state: ENABLED
  permission: READ_ONLY
}
