# build/release/aconfig/bp2a/com.android.nfc.flags/exit_frames_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.nfc.flags"
  name: "exit_frames"
  state: ENABLED
  permission: READ_ONLY
}
