# build/release/aconfig/bp2a/com.android.nfc.flags/nfc_alert_tag_app_launch_flag_values.textproto : ENABLED
flag_value {
  package: "com.android.nfc.flags"
  name: "nfc_alert_tag_app_launch"
  state: ENABLED
  permission: READ_ONLY
}
