flag_value {
  package: "com.google.android.apps.pixel.support.boostdatalib.core.flags"
  name: "enable_bdl_example_signal_api"
  state: ENABLED
  permission: READ_ONLY
  # container: system_ext
  # namespace: pixel_support
  # bug: 356971058
  # description: This flag controls whether example signal api is enabled.
  # trace: vendor/google/apps/PersistentBackgroundServices/adapter/boostdatalayer/src/com/google/android/apps/pixel/support/boostdatalib/core/flags/aconfig/flag_declarations.aconfig : DISABLED
  # trace: vendor/google/release/aconfig/bp3a/com.google.android.apps.pixel.support.boostdatalib.core.flags/enable_bdl_example_signal_api_flag_values.textproto : ENABLED
}
