flag_value {
  package: "com.android.server.usb.flags"
  name: "check_user_action_unlocked"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: usb
  # bug: 73654179
  # description: This flag checks if phone is unlocked after boot
  # trace: frameworks/base/services/usb/java/com/android/server/usb/flags/usb_flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/com.android.server.usb.flags/check_user_action_unlocked_flag_values.textproto : ENABLED
}
