flag_value {
  package: "com.android.text.flags"
  name: "fix_line_height_for_locale"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: text
  # bug: 303326708
  # description: Feature flag that preserve the line height of the TextView and EditText even if the the locale is different from Latin
  # trace: frameworks/base/core/java/android/text/flags/24Q3.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/com.android.text.flags/fix_line_height_for_locale_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/com.android.text.flags/fix_line_height_for_locale_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/com.android.text.flags/fix_line_height_for_locale_flag_values.textproto : ENABLED
}
