flag_value {
  package: "com.android.text.flags"
  name: "handwriting_track_disabled"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: text
  # purpose: PURPOSE_BUGFIX
  # bug: 361256391
  # description: Handwriting initiator tracks focused view even if handwriting is disabled to fix initiation bug.
  # trace: frameworks/base/core/java/android/text/flags/flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp1a/com.android.text.flags/handwriting_track_disabled_flag_values.textproto : ENABLED
}
