# build/release/aconfig/bp2a/android.car.feature/android_b_vehicle_properties_flag_values.textproto : ENABLED
flag_value {
  package: "android.car.feature"
  name: "android_b_vehicle_properties"
  state: ENABLED
  permission: READ_ONLY
}
