# build/release/aconfig/bp2a/android.car.feature/car_input_start_btpairing_lptt_flag_values.textproto : ENABLED
flag_value {
  package: "android.car.feature"
  name: "car_input_start_btpairing_lptt"
  state: ENABLED
  permission: READ_ONLY
}
