flag_value {
  package: "android.companion.virtualdevice.flags"
  name: "high_resolution_scroll"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: virtual_devices
  # bug: 335160780
  # description: Enable high resolution scroll
  # trace: frameworks/base/core/java/android/companion/virtual/flags/flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/android.companion.virtualdevice.flags/high_resolution_scroll_flag_values.textproto : ENABLED
}
