flag_value {
  package: "android.companion.virtualdevice.flags"
  name: "notifications_for_device_streaming"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: virtual_devices
  # bug: 375240276
  # description: Add notifications permissions to device streaming role
  # trace: frameworks/base/core/java/android/companion/virtual/flags/flags.aconfig : DISABLED
  # trace: build/release/aconfig/bp2a/android.companion.virtualdevice.flags/notifications_for_device_streaming_flag_values.textproto : ENABLED
}
