flag_value {
  package: "android.credentials.flags"
  name: "clear_credentials_fix_enabled"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: credential_manager
  # purpose: PURPOSE_BUGFIX
  # bug: 314926460
  # description: Fixes bug in clearCredential API that causes indefinite suspension
  # trace: frameworks/base/core/java/android/credentials/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.credentials.flags/clear_credentials_fix_enabled_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.credentials.flags/clear_credentials_fix_enabled_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.credentials.flags/clear_credentials_fix_enabled_flag_values.textproto : ENABLED
}
