flag_value {
  package: "android.credentials.flags"
  name: "clear_session_enabled"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: credential_manager
  # bug: 308470501
  # description: Enables clearing of Credential Manager sessions when client process dies
  # trace: frameworks/base/core/java/android/credentials/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap3a/android.credentials.flags/clear_session_enabled_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/ap4a/android.credentials.flags/clear_session_enabled_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.credentials.flags/clear_session_enabled_flag_values.textproto : ENABLED
}
