flag_value {
  package: "android.credentials.flags"
  name: "wear_credential_manager_enabled"
  state: ENABLED
  permission: READ_ONLY
  # container: system
  # namespace: wear_frameworks
  # bug: 301168341
  # description: Enables Credential Manager on Wear Platform
  # trace: frameworks/base/core/java/android/credentials/flags.aconfig : DISABLED
  # trace: build/release/aconfig/ap4a/android.credentials.flags/wear_credential_manager_enabled_flag_values.textproto : ENABLED
  # trace: build/release/aconfig/bp1a/android.credentials.flags/wear_credential_manager_enabled_flag_values.textproto : ENABLED
}
